/*
 * # Smart Contract Audit
 * A single Lamatic flow that accepts Solidity source code and returns a structured AI-assisted audit report covering security, gas, and best-practice concerns.
 *
 * ## Purpose
 * This flow adapts the ContractSLM/SolidityGuard idea into AgentKit form. Instead of exposing an RL-style reset/step environment, it gives developers a direct request-response audit copilot that can be used from a web UI or API client.
 *
 * The flow solves the practical first-pass review problem: developers can paste a Solidity contract, select the review mode they care about, and receive categorized findings with severity, impact, confidence, and remediation guidance. It is intentionally scoped as an engineering assistant rather than a formal security certification.
 *
 * ## When To Use
 * - Use when a developer wants a fast pre-audit pass over Solidity source code.
 * - Use when the caller can provide raw contract code through `contractCode`.
 * - Use when findings should be grouped into security, gas, and best-practice categories.
 * - Use when a Next.js application needs a stable Lamatic flow ID to execute the review.
 *
 * ## When Not To Use
 * - Do not use as a replacement for professional security audits, fuzzing, symbolic execution, invariant testing, or formal verification.
 * - Do not use for private-key, seed-phrase, wallet-draining, exploit-deployment, or live-protocol abuse workflows.
 * - Do not use when the contract depends on unavailable external files unless the caller includes enough context in `contractCode` or `focusAreas`.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `contractCode` | `string` | Yes | Solidity source code to review. |
 * | `contractName` | `string` | No | Optional display name for the contract. |
 * | `auditMode` | `string` | Yes | One of `security`, `gas`, `best-practices`, or `comprehensive`. |
 * | `focusAreas` | `string` | No | Optional extra review guidance from the caller. |
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `audit` | `string` | JSON-formatted audit report generated by the LLM node. |
 *
 * The application layer parses the `audit` field into an object and falls back to rendering the raw text if the model returns malformed JSON.
 */

// Flow: smart-contract-audit

export const meta = {
  name: "Smart Contract Audit",
  description:
    "Reviews Solidity source code and returns a structured report covering vulnerabilities, gas optimizations, and best-practice issues.",
  tags: ["solidity", "security", "audit", "web3"],
  testInput: {
    contractName: "Vault",
    auditMode: "comprehensive",
    focusAreas: "reentrancy and access control",
    contractCode:
      "pragma solidity ^0.8.20; contract Vault { mapping(address => uint256) public balances; function withdraw() external { uint256 amount = balances[msg.sender]; (bool ok,) = msg.sender.call{value: amount}(\"\"); require(ok); balances[msg.sender] = 0; } }",
  },
  githubUrl:
    "https://github.com/Lamatic/AgentKit/tree/main/kits/smart-contract-audit-copilot",
  documentationUrl:
    "https://github.com/Lamatic/AgentKit/tree/main/kits/smart-contract-audit-copilot/README.md",
  deployUrl: "",
  author: {
    name: "Tanay Mitra",
    email: "tanaymitra54@users.noreply.github.com",
  },
};

export const inputs = {
  LLMNode_421: [
    {
      name: "generativeModelName",
      label: "Generative Model Name",
      type: "model",
      modelType: "generator/text",
      mode: "chat",
      description: "Select the model to generate the smart contract audit report.",
      required: true,
      defaultValue: [
        {
          configName: "configA",
          type: "generator/text",
          provider_name: "",
          credential_name: "",
          params: {},
        },
      ],
      typeOptions: {
        loadOptionsMethod: "listModels",
      },
      isPrivate: true,
    },
  ],
};

export const references = {
  constitutions: {
    default: "@constitutions/default.md",
  },
  prompts: {
    smart_contract_audit_system: "@prompts/smart-contract-audit_system.md",
    smart_contract_audit_user: "@prompts/smart-contract-audit_user.md",
  },
  modelConfigs: {
    smart_contract_audit_llm: "@model-configs/smart-contract-audit_llm.ts",
  },
};

export const nodes = [
  {
    id: "triggerNode_1",
    type: "triggerNode",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      nodeId: "graphqlNode",
      trigger: true,
      values: {
        id: "triggerNode_1",
        nodeName: "API Request",
        responeType: "realtime",
        advance_schema: "",
      },
    },
  },
  {
    id: "LLMNode_421",
    type: "dynamicNode",
    position: {
      x: 320,
      y: 0,
    },
    data: {
      nodeId: "LLMNode",
      values: {
        nodeName: "Generate Audit Report",
        tools: [],
        prompts: [
          {
            id: "6f1e5d68-4a35-4c52-a220-smart-contract-audit-system",
            role: "system",
            content: "@prompts/smart-contract-audit_system.md",
          },
          {
            id: "6f1e5d68-4a35-4c52-a220-smart-contract-audit-user",
            role: "user",
            content: "@prompts/smart-contract-audit_user.md",
          },
        ],
        memories: "@model-configs/smart-contract-audit_llm.ts",
        messages: "@model-configs/smart-contract-audit_llm.ts",
        attachments: "@model-configs/smart-contract-audit_llm.ts",
        credentials: "@model-configs/smart-contract-audit_llm.ts",
        generativeModelName: "@model-configs/smart-contract-audit_llm.ts",
      },
    },
  },
  {
    id: "graphqlResponseNode_689",
    type: "dynamicNode",
    position: {
      x: 640,
      y: 0,
    },
    data: {
      nodeId: "graphqlResponseNode",
      values: {
        id: "graphqlResponseNode_689",
        headers: "{}",
        retries: "0",
        nodeName: "API Response",
        webhookUrl: "",
        retry_delay: "0",
        outputMapping:
          '{\n  "audit": "{{LLMNode_421.output.generatedResponse}}"\n}',
      },
    },
  },
];

export const edges = [
  {
    id: "triggerNode_1-LLMNode_421",
    source: "triggerNode_1",
    target: "LLMNode_421",
    sourceHandle: "bottom",
    targetHandle: "top",
    type: "defaultEdge",
  },
  {
    id: "LLMNode_421-graphqlResponseNode_689",
    source: "LLMNode_421",
    target: "graphqlResponseNode_689",
    sourceHandle: "bottom",
    targetHandle: "top",
    type: "defaultEdge",
  },
  {
    id: "response-graphqlResponseNode_689",
    source: "triggerNode_1",
    target: "graphqlResponseNode_689",
    sourceHandle: "to-response",
    targetHandle: "from-trigger",
    type: "responseEdge",
  },
];

export default { meta, inputs, references, nodes, edges };
