// types/response.ts
// Full TypeScript interfaces matching the TrustGuard AI flow output schema.
// NOTE: For runtime-validated types, prefer ValidatedInvestigationResponse
// from @/lib/schemas (Zod-inferred). These interfaces remain for components
// that receive already-validated data.

/**
 * Metadata about the investigation created by the Lamatic flow planner stage.
 * Contains the unique investigation ID, title, category, current status,
 * workflow name, and the detected language of the analysed content.
 */
export interface InvestigationInfo {
  readonly id: string;
  readonly title: string;
  readonly category: string;
  readonly status: string;
  readonly workflow: string;
  readonly language: string;
}

/**
 * Sanitised and summarised form of the user-submitted content, produced by
 * the evidence extractor stage.  `clean_text` is the de-noised plain-text
 * version, `summary` is a short AI-generated description, and
 * `detected_input_type` reflects the automatically identified content type.
 */
export interface NormalizedContent {
  readonly clean_text: string;
  readonly summary: string;
  readonly detected_input_type: string;
}

/**
 * Structured evidence items extracted from the content by the evidence
 * extractor stage.  Each field is an array of matched strings belonging
 * to that evidence category (URLs, domains, emails, phone numbers, money
 * amounts, brands, urgency phrases, attachments, languages, and named entities).
 */
export interface EvidenceData {
  readonly urls: readonly string[];
  readonly domains: readonly string[];
  readonly emails: readonly string[];
  readonly phone_numbers: readonly string[];
  readonly money_amounts: readonly string[];
  readonly brands: readonly string[];
  readonly urgency_phrases: readonly string[];
  readonly attachments: readonly string[];
  readonly languages: readonly string[];
  readonly entities: readonly string[];
}

/**
 * Grouped threat indicator strings produced by the threat analyser stage.
 * Indicators are bucketed into `high`, `medium`, and `low` severity lists
 * to make risk prioritisation straightforward for both UI rendering and
 * downstream processing.
 */
export interface ThreatIndicators {
  readonly high: readonly string[];
  readonly medium: readonly string[];
  readonly low: readonly string[];
}

/**
 * Threat analysis produced by the threat analyser stage.
 * Contains the numeric `risk_score` (0–100) and `confidence` (0–100) values,
 * the overall `severity` classification, grouped `indicators`, a list of
 * `matched_patterns`, `missing_information` flags, and a free-text
 * `reasoning_summary` generated by the LLM.
 */
export interface ThreatAnalysis {
  readonly risk_score: number;
  readonly confidence: number;
  /** Discriminated severity union — use Zod schema for runtime unknown values. */
  readonly severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  readonly indicators: ThreatIndicators;
  readonly matched_patterns: readonly string[];
  readonly missing_information: readonly string[];
  readonly reasoning_summary: string;
}

/**
 * Final decision output produced by the decision engine stage.
 * Includes the free-text `classification` label (e.g. "SCAM", "SAFE"),
 * the `final_verdict` sentence, `recommended_action` for the recipient,
 * `decision_reason` explaining the ruling, `priority` level, and a
 * `human_review` flag indicating whether a human analyst should verify.
 */
export interface DecisionData {
  readonly classification: string;
  readonly final_verdict: string;
  readonly recommended_action: string;
  readonly decision_reason: string;
  readonly priority: string;
  readonly human_review: boolean;
}

/**
 * Housekeeping metadata appended to every Lamatic flow response.
 * Records the `workflow` name and the `version` string of the flow
 * definition that produced the response, useful for debugging and auditing.
 */
export interface ResponseMetadata {
  readonly workflow: string;
  readonly version: string;
}

/**
 * Root response shape returned by the TrustGuard AI Lamatic flow.
 * Aggregates all stage outputs — investigation metadata, normalised content,
 * extracted evidence, threat analysis, the final decision, and flow metadata —
 * into a single object consumed by the UI result cards.
 */
export interface InvestigationResponse {
  readonly investigation: InvestigationInfo;
  readonly normalized: NormalizedContent;
  readonly evidence: EvidenceData;
  readonly analysis: ThreatAnalysis;
  readonly decision: DecisionData;
  readonly metadata: ResponseMetadata;
}

// Input form shape
/** Union of supported content input types selectable in the investigation form. */
export type InputType = "Email" | "SMS" | "URL" | "Document" | "Text";
/** Union of supported language options for the investigation form language selector. */
export type LanguageOption = "Auto" | "English" | "Hindi" | "Bengali";

/**
 * Shape of the investigation input form data collected from the user.
 * Passed directly to the `runInvestigation` server action which normalises
 * it into the Lamatic flow payload before dispatching the API call.
 */
export interface AnalyzeFormData {
  input_type: InputType;
  content: string;
  attachment_url: string;
  language: LanguageOption;
  memory_enabled: boolean;
}
