// types/response.ts
// Full TypeScript types for the TrustGuard AI flow output schema.
// All types are derived from the canonical Zod schemas in @/lib/schemas so
// that compile-time and runtime shapes are always in sync.
// NOTE: For runtime-validated types, prefer ValidatedInvestigationResponse
// from @/lib/schemas (Zod-inferred). These types remain for components
// that receive already-validated data.

import { z } from "zod";
import {
  InvestigationResponseSchema,
} from "@/lib/schemas";

// ---------------------------------------------------------------------------
// Re-export the root validated type used by the server action and page.
// ---------------------------------------------------------------------------

/**
 * Root response shape returned by the TrustGuard AI Lamatic flow.
 * Aggregates all stage outputs — investigation metadata, normalised content,
 * extracted evidence, threat analysis, the final decision, and flow metadata —
 * into a single object consumed by the UI result cards.
 *
 * Derived from {@link InvestigationResponseSchema} so runtime and
 * compile-time shapes are always in sync.
 */
export type InvestigationResponse = z.infer<typeof InvestigationResponseSchema>;

// ---------------------------------------------------------------------------
// Sub-types extracted from the root schema for convenient component imports.
// ---------------------------------------------------------------------------

/**
 * Metadata about the investigation created by the Lamatic flow planner stage.
 * Contains the unique investigation ID, title, category, current status,
 * workflow name, and the detected language of the analysed content.
 */
export type InvestigationInfo = InvestigationResponse["investigation"];

/**
 * Sanitised and summarised form of the user-submitted content, produced by
 * the evidence extractor stage.  `clean_text` is the de-noised plain-text
 * version, `summary` is a short AI-generated description, and
 * `detected_input_type` reflects the automatically identified content type.
 */
export type NormalizedContent = InvestigationResponse["normalized"];

/**
 * Structured evidence items extracted from the content by the evidence
 * extractor stage.  Each field is an array of matched strings belonging
 * to that evidence category (URLs, domains, emails, phone numbers, money
 * amounts, brands, urgency phrases, attachments, languages, and named entities).
 */
export type EvidenceData = InvestigationResponse["evidence"];

/**
 * Grouped threat indicator strings produced by the threat analyser stage.
 * Indicators are bucketed into `high`, `medium`, and `low` severity lists
 * to make risk prioritisation straightforward for both UI rendering and
 * downstream processing.
 */
export type ThreatIndicators = InvestigationResponse["analysis"]["indicators"];

/**
 * Threat analysis produced by the threat analyser stage.
 * Contains the numeric `risk_score` (0–100) and `confidence` (0–100) values,
 * the overall `severity` classification, grouped `indicators`, a list of
 * `matched_patterns`, `missing_information` flags, and a free-text
 * `reasoning_summary` generated by the LLM.
 */
export type ThreatAnalysis = InvestigationResponse["analysis"];

/**
 * Final decision output produced by the decision engine stage.
 * Includes the free-text `classification` label (e.g. "SCAM", "SAFE"),
 * the `final_verdict` sentence, `recommended_action` for the recipient,
 * `decision_reason` explaining the ruling, `priority` level, and a
 * `human_review` flag indicating whether a human analyst should verify.
 */
export type DecisionData = InvestigationResponse["decision"];

/**
 * Housekeeping metadata appended to every Lamatic flow response.
 * Records the `workflow` name and the `version` string of the flow
 * definition that produced the response, useful for debugging and auditing.
 */
export type ResponseMetadata = InvestigationResponse["metadata"];

// ---------------------------------------------------------------------------
// Input form types — no Zod equivalent; kept as plain TypeScript types.
// ---------------------------------------------------------------------------

/** Union of supported content input types selectable in the investigation form. */
export type InputType = "Email" | "SMS" | "URL" | "Document" | "Text";
/** Union of supported language options for the investigation form language selector. */
export type LanguageOption = "Auto" | "English" | "Hindi" | "Bengali";

/**
 * Shape of the investigation input form data collected from the user.
 * Passed directly to the `runInvestigation` server action which normalises
 * it into the Lamatic flow payload before dispatching the API call.
 */
export interface AnalyzeFormData {
  input_type: InputType;
  content: string;
  attachment_url: string;
  language: LanguageOption;
  memory_enabled: boolean;
}
