import { SMCAnalysis } from "@/lib/types";

const BIAS_STYLES: Record<string, { text: string; bg: string; dot: string }> = {
  bullish: { text: "text-bull", bg: "bg-bull/10", dot: "bg-bull" },
  bearish: { text: "text-bear", bg: "bg-bear/10", dot: "bg-bear" },
  neutral: { text: "text-muted", bg: "bg-muted/10", dot: "bg-muted" },
};

export default function BiasCard({
  analysis,
  reasoning,
  source,
}: {
  analysis: SMCAnalysis;
  reasoning: string;
  source: "lamatic" | "fallback";
}) {
  const style = BIAS_STYLES[analysis.bias];

  return (
    <div className="animate-fade-up rounded-lg border border-border bg-panel p-5 flex flex-col gap-5">
      <div className="flex items-center justify-between">
        <div className={`inline-flex items-center gap-2 rounded-full px-3 py-1 ${style.bg}`}>
          <span className={`h-2 w-2 rounded-full ${style.dot}`} />
          <span className={`font-display font-medium uppercase tracking-wide text-sm ${style.text}`}>
            {analysis.bias}
          </span>
        </div>
        <span className="font-mono tabular text-sm text-muted">{analysis.confidence}% confidence</span>
      </div>

      <p className="text-sm leading-relaxed text-ink/90">{reasoning}</p>

      <div className="flex flex-col gap-2">
        <span className="text-xs uppercase tracking-wide text-muted">Key levels</span>
        {analysis.keyLevels.length === 0 && <span className="text-sm text-muted">No active zones detected.</span>}
        {analysis.keyLevels.map((level, i) => (
          <div key={i} className="flex items-center justify-between border-t border-border pt-2 text-sm">
            <div className="flex flex-col">
              <span className="text-ink/90">{level.label}</span>
              <span className="text-xs text-muted">{level.detail}</span>
            </div>
            <span className="font-mono tabular text-ink/90">
              {level.low === level.high
                ? level.low.toFixed(level.low < 10 ? 4 : 1)
                : `${level.low.toFixed(level.low < 10 ? 4 : 1)}–${level.high.toFixed(level.high < 10 ? 4 : 1)}`}
            </span>
          </div>
        ))}
      </div>

      <span className="text-xs text-muted">
        {source === "lamatic" ? "Narrative generated by your Lamatic flow." : "Narrative generated locally (no LAMATIC_API_KEY configured)."}
      </span>
    </div>
  );
}
