/*
 * # Image-Based Product Identification
 * This flow accepts an API request containing an image URL, uses an LLM-driven analysis step to identify products in the image, and returns normalized product data as the entry-point execution path for the wider image-to-structured-data pipeline.
 *
 * ## Purpose
 * This flow is responsible for converting a raw image link into structured product identification data that downstream software can consume reliably. Its specific job is to receive an inbound API payload, pass the image URL into a model-guided interpretation step, and transform the model response into a predictable JSON structure containing product-oriented details. That solves the core sub-task of turning unstructured visual input, referenced by URL, into machine-readable output without requiring the caller to parse free-form model text.
 *
 * The outcome of the flow is a response payload under `image_data` that contains the post-processed result from the `Code` node. In practical terms, this gives applications a stable contract for catalog enrichment, compliance workflows, marketplace tooling, or other automation that needs product names, descriptions, and shopping links extracted from images. That structured output matters because it reduces ambiguity at the boundary between AI inference and operational systems.
 *
 * In the broader agent context, this flow sits at the front of the pipeline as the system's API-facing entry point. The parent agent definition describes a single-flow architecture, so there is no separate retrieval or orchestration stage before this one. Instead, this flow combines request intake, model inference, and response shaping in one execution path: receive the image URL, synthesize product understanding with the LLM, normalize the result in code, and return it for direct use or chaining by external systems.
 *
 * ## When To Use
 * - Use when a caller has a publicly reachable image URL and needs automated identification of one or more products visible in that image.
 * - Use when the desired output must be structured JSON rather than free-form descriptive text.
 * - Use when this capability needs to be exposed behind an API boundary for application-to-application invocation.
 * - Use when downstream automation requires normalized product fields such as a product name, description, and shopping link.
 * - Use when an external workflow wants a compact single-call flow that handles intake, AI inference, and output shaping together.
 *
 * ## When Not To Use
 * - Do not use when the input is a raw image file, binary upload, or base64 payload instead of a URL; this flow is designed around an inbound `url` field.
 * - Do not use when the image URL is not publicly accessible by the model or execution environment.
 * - Do not use when the task requires deterministic computer-vision labeling, OCR-specific extraction, or exact product database lookup rather than model-based identification.
 * - Do not use when there is no image to analyze and the request is text-only.
 * - Do not use when a different flow in your system is responsible for post-identification actions such as catalog insertion, approval routing, or commerce execution; this flow only identifies and structures the image-derived result.
 * - Do not use if your integration requires a guaranteed fixed schema beyond what the `Code` node normalizes and validates, unless you have inspected and approved that script's exact behavior.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `url` | `string` | Yes | Publicly reachable URL of the image to analyze for product identification. |
 *
 * The trigger definition does not declare a formal advanced schema, so validation is largely an execution-time assumption rather than a strict contract enforced in the flow source. The `url` value should point to a valid image resource reachable by the model. The parent agent context indicates this field is referenced internally as `{{triggerNode_1.output.url}}`, so requests that omit it or provide a non-image link are likely to produce low-quality or failed results.
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `image_data` | `object` | Structured, post-processed product identification result generated by the `Code` node from the LLM output. |
 *
 * The API response is a structured object with a top-level field named `image_data`. That field contains whatever normalized JSON the `Code` node emits after processing the model response. Based on the flow description and parent agent context, this payload is intended to represent identified product data such as product name, description, and shopping link, potentially covering multiple objects in one image. Because the exact schema is enforced in the referenced script rather than the flow source itself, callers should treat `image_data` as structured but script-defined, and verify the script contract if they need strict field guarantees.
 *
 * ## Dependencies
 * ### Upstream Flows
 * - None. This is a standalone entry-point flow invoked directly through the `API Request` trigger.
 * - No prior Lamatic flow must execute before this one.
 * - The only required upstream data is the inbound API payload field `url`, supplied by the external caller rather than another flow.
 *
 * ### Downstream Flows
 * - No downstream Lamatic flows are defined in the provided project data.
 * - In the broader system, external applications or workflows may consume `image_data` for catalog enrichment, compliance review, marketplace tooling, or further commerce automation, but no explicit in-repo flow dependency is declared.
 *
 * ### External Services
 * - Lamatic GraphQL/API trigger and response layer — receives the inbound request and returns the final payload — required credential or environment variable not explicitly declared in the flow source.
 * - Configured LLM from `@model-configs/image-based-product-identification_generate-text.ts` — interprets the image URL context and generates product-identification text — model-specific credential or provider environment variable is required but not exposed in the flow source.
 *
 * ### Environment Variables
 * - No environment variables are explicitly declared in the provided flow source.
 * - Model/provider credentials are likely required by the `Generate Text` node through `@model-configs/image-based-product-identification_generate-text.ts`, but the exact variable names are not visible here.
 * - If your Lamatic workspace or model provider requires API keys, they are used indirectly by `Generate Text` and must be configured at the workspace or model-config level.
 *
 * ## Node Walkthrough
 * 1. `API Request` (`graphqlNode`) receives the external API call that starts the flow. This node is the trigger and is expected to receive a payload containing `url`, the image link that the rest of the flow will analyze.
 * 2. `Generate Text` (`LLMNode`) runs next and uses the referenced system prompt plus the configured model settings from `@model-configs/image-based-product-identification_generate-text.ts`. In this flow, the node's purpose is to interpret the image URL supplied by the trigger and generate product-oriented identification output. The parent agent context indicates the prompt references `{{triggerNode_1.output.url}}`, so the model is instructed using the incoming image link as the central input.
 * 3. `Code` (`codeNode`) post-processes the raw output from `Generate Text` using the script `@scripts/image-based-product-identification_code.ts`. This is the normalization step that converts model output into cleaner structured JSON suitable for API consumers. In this flow, it is the key boundary between flexible LLM text generation and predictable response formatting.
 * 4. `API Response` (`graphqlResponseNode`) returns the final result to the caller. Its output mapping wraps the `Code` node result into a top-level response field named `image_data`, so the external API consumer receives `{ image_data: ... }` as the response shape.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | Request returns an error before model execution | Missing or malformed `url` in the inbound payload | Send a valid request body containing a non-empty `url` field that points to an image resource. |
 * | Response is empty or low quality | The provided `url` does not resolve to a public image, points to unsupported content, or the image is ambiguous | Verify that the URL is publicly reachable, returns an actual image, and contains the product clearly enough for model interpretation. |
 * | Model step fails at runtime | Missing model credentials or incomplete provider configuration in the Lamatic workspace or referenced model config | Confirm that the credentials required by `@model-configs/image-based-product-identification_generate-text.ts` are configured and valid. |
 * | Response shape is not what the caller expects | The `Code` node script normalizes output differently than the consumer assumes | Inspect and align against `@scripts/image-based-product-identification_code.ts`, then update either the consumer contract or the script. |
 * | `image_data` is present but missing expected fields such as product name or shopping link | The model could not confidently infer those details from the image alone, or the script does not guarantee all fields in every case | Improve image quality, provide clearer product imagery, and review the prompt and code script for fallback handling. |
 * | Invocation fails in a chained workflow | An external orchestrator called this flow without supplying the required `url` from a previous step | Ensure the upstream system maps its output into this flow's required `url` input before invocation. |
 * | Timeout or slow execution | Model inference latency or delayed access to the remote image URL | Use fast, stable image hosting and validate model/provider performance settings in the referenced model configuration. |
 *
 * ## Notes
 * - The flow source declares no explicit trigger schema, so input validation should be enforced by the caller or added at the API boundary if stricter guarantees are required.
 * - The exact prompt text, model selection, and normalization logic live in referenced files rather than inline node configuration. For production-grade integration, review `@prompts/image-based-product-identification_generate-text_system.md`, `@model-configs/image-based-product-identification_generate-text.ts`, and `@scripts/image-based-product-identification_code.ts` together.
 * - Although the high-level description mentions returning product name, description, and shopping link, the parent agent context also notes support for identifying multiple objects in one image. Consumers should therefore be prepared for `image_data` to represent either a single identified product or a collection, depending on how the code script structures the result.
 * - There is no explicit branching or conditional logic in the flow graph; execution is linear from request to model to code to response.
 * - The flow is best treated as an AI-assisted identification step, not as a verified product catalog lookup. If downstream actions carry compliance or commercial risk, add human review or a validation layer after this flow.
 */

// Flow: image-based-product-identification

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Image-Based Product Identification",
  "description": "This flow builds an AI-powered product identification system that processes image links, identifies products, and generates a structured JSON output with product name, description, and shopping link, enabling seamless analysis and data extraction from images.",
  "tags": [
    "🚀 Startup",
    "🔒 Compliance"
  ],
  "testInput": null,
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": "https://studio.lamatic.ai/template/image-based-product-identification",
  "author": {
    "name": "Naitik Kapadia",
    "email": "naitikk@lamatic.ai"
  }
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {};

// ── References ────────────────────────────────────────
// Cross-references to extracted resources in their own directories
// NOTE: Trigger widget settings are saved to triggers/widgets/ but NOT cross-referenced here
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "image_based_product_identification_generate_text_system": "@prompts/image-based-product-identification_generate-text_system.md"
  },
  "scripts": {
    "image_based_product_identification_code": "@scripts/image-based-product-identification_code.ts"
  },
  "modelConfigs": {
    "image_based_product_identification_generate_text": "@model-configs/image-based-product-identification_generate-text.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "type": "triggerNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlNode",
      "trigger": true,
      "values": {
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": ""
      }
    }
  },
  {
    "id": "LLMNode_918",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "LLMNode",
      "values": {
        "nodeName": "Generate Text",
        "tools": [],
        "prompts": [
          {
            "id": "ac649ac6-3c1c-4a20-a7fe-a583d11519ae",
            "role": "system",
            "content": "@prompts/image-based-product-identification_generate-text_system.md"
          }
        ],
        "memories": "@model-configs/image-based-product-identification_generate-text.ts",
        "messages": "@model-configs/image-based-product-identification_generate-text.ts",
        "generativeModelName": "@model-configs/image-based-product-identification_generate-text.ts"
      }
    }
  },
  {
    "id": "codeNode_743",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "codeNode",
      "values": {
        "nodeName": "Code",
        "code": "@scripts/image-based-product-identification_code.ts"
      }
    }
  },
  {
    "id": "graphqlResponseNode_410",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlResponseNode",
      "values": {
        "nodeName": "API Response",
        "outputMapping": "{\n  \"image_data\": \"{{codeNode_743.output}}\"\n}"
      }
    }
  }
];

export const edges = [
  {
    "id": "triggerNode_1-LLMNode_918",
    "source": "triggerNode_1",
    "target": "LLMNode_918",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "LLMNode_918-codeNode_743",
    "source": "LLMNode_918",
    "target": "codeNode_743",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "codeNode_743-graphqlResponseNode_410",
    "source": "codeNode_743",
    "target": "graphqlResponseNode_410",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "response-graphqlResponseNode_410",
    "source": "triggerNode_1",
    "target": "graphqlResponseNode_410",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger",
    "type": "responseEdge"
  }
];

export default { meta, inputs, references, nodes, edges };
