// Flow: blog-writer-agent
// When @lamatic/sdk ships: import { defineFlow } from '@lamatic/sdk'

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Blog Writer Agent",
  "description": "This automation generates a blog on any given topic by searching the internet for the most relevant source, then writing the blog in the user's desired tone.",
  "tags": [
    "✨ Generative"
  ],
  "testInput": null,
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": "https://studio.lamatic.ai/template/blog-writer-agent",
  "author": {
    "name": "Naitik Kapadia",
    "email": "naitikk@lamatic.ai"
  }
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {};

// ── References ────────────────────────────────────────
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "blog_writer_agent_supervisor_system": "@prompts/blog-writer-agent_supervisor_system.md",
    "blog_writer_agent_generate_text_user": "@prompts/blog-writer-agent_generate-text_user.md",
    "blog_writer_agent_generate_text_system": "@prompts/blog-writer-agent_generate-text_system.md"
  },
  "scripts": {
    "blog_writer_agent_extract_link": "@scripts/blog-writer-agent_extract-link.ts",
    "blog_writer_agent_extract_final_content": "@scripts/blog-writer-agent_extract-final-content.ts"
  }
};

// ── Nodes & Edges (exact Lamatic Studio export) ───────
export const nodes = [
  {
    "id": "triggerNode_1",
    "type": "triggerNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlNode",
      "trigger": true,
      "values": {
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": "{\n  \"topic\": \"string\",\n  \"tone\": \"string\"\n}"
      }
    }
  },
  {
    "id": "agentNode_901",
    "type": "agentNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "agentNode",
      "values": {
        "nodeName": "Supervisor",
        "tools": [],
        "agents": [
          {
            "name": "Researcher",
            "schema": "{\n  \"type\": \"object\",\n  \"properties\": {}\n}",
            "description": "This team will search the internet for the given topic and then scrape from that link"
          },
          {
            "name": "Writer",
            "schema": "{\n  \"type\": \"object\",\n  \"properties\": {\n    \"research\": {\n      \"type\": \"string\",\n      \"required\": true,\n      \"description\": \"This implies the final research fetched by the research team, which is supposed to be passed to the writing team\"\n    }\n  }\n}",
            "description": "This team will write an informative blog given the research from the research team"
          },
          {
            "name": "Editor",
            "schema": "{\n  \"type\": \"object\",\n  \"properties\": {\n    \"writeup\": {\n      \"type\": \"string\",\n      \"required\": true,\n      \"description\": \"This implies the written content generated by the writing team\"\n    }\n  }\n}",
            "description": "This team will edit the writeup given by the writing team based on the tone given by the user"
          }
        ],
        "prompts": [
          {
            "id": "2e9025c8-a909-471f-a3b0-44b6bc55fb9a",
            "role": "system",
            "content": "@prompts/blog-writer-agent_supervisor_system.md"
          },
          {
            "id": "0780d9a4-deb5-4b0b-81a2-503e770a6f4e",
            "role": "system",
            "content": "@prompts/blog-writer-agent_supervisor_system.md"
          }
        ],
        "messages": "[]",
        "stopWord": "",
        "connectedTo": "agentLoopEndNode_399",
        "maxIterations": 5,
        "generativeModelName": {}
      }
    }
  },
  {
    "id": "agentLoopEndNode_399",
    "type": "agentLoopEndNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "agentLoopEndNode",
      "values": {
        "nodeName": "Agent Loop End",
        "connectedTo": "agentNode_901"
      }
    }
  },
  {
    "id": "webSearchNode_683",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "webSearchNode",
      "values": {
        "nodeName": "Web Search",
        "page": 1,
        "type": "https://google.serper.dev/search",
        "query": "{{triggerNode_1.output.topic}}",
        "country": "",
        "results": "5",
        "language": "",
        "location": "",
        "dateRange": "",
        "credentials": "SERPER_API_KEY"
      }
    }
  },
  {
    "id": "LLMNode_814",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "LLMNode",
      "values": {
        "nodeName": "Generate Text",
        "tools": [],
        "prompts": [
          {
            "id": "d687c0ca-c3ff-462c-88be-6545760bc8a7",
            "role": "user",
            "content": "@prompts/blog-writer-agent_generate-text_user.md"
          },
          {
            "id": "9db3a7b8-03e0-4dc5-9072-368c98498399",
            "role": "system",
            "content": "@prompts/blog-writer-agent_generate-text_system.md"
          }
        ],
        "memories": "[]",
        "messages": "[]",
        "generativeModelName": {}
      }
    }
  },
  {
    "id": "LLMNode_882",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "LLMNode",
      "values": {
        "nodeName": "Generate Text",
        "tools": [],
        "prompts": [
          {
            "id": "f1d70f1e-4e74-4efd-825b-75e93e377783",
            "role": "user",
            "content": "@prompts/blog-writer-agent_generate-text_user.md"
          },
          {
            "id": "d24c6193-cb2b-4420-98a3-527f1c249df6",
            "role": "system",
            "content": "@prompts/blog-writer-agent_generate-text_system.md"
          }
        ],
        "memories": "[]",
        "messages": "[]",
        "generativeModelName": {}
      }
    }
  },
  {
    "id": "codeNode_317",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "codeNode",
      "values": {
        "nodeName": "Extract Link",
        "code": "@scripts/blog-writer-agent_extract-link.ts"
      }
    }
  },
  {
    "id": "scraperNode_331",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "scraperNode",
      "values": {
        "nodeName": "Scraper",
        "url": "{{codeNode_317.output}}",
        "mobile": false,
        "waitFor": "250",
        "credentials": "FIRECRAWL_API_KEY",
        "excludeTags": [],
        "includeTags": [],
        "onlyMainContent": true,
        "skipTLsVerification": false
      }
    }
  },
  {
    "id": "codeNode_604",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "codeNode",
      "values": {
        "nodeName": "Extract Final Content",
        "code": "@scripts/blog-writer-agent_extract-final-content.ts"
      }
    }
  },
  {
    "id": "graphqlResponseNode_937",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlResponseNode",
      "values": {
        "nodeName": "API Response",
        "outputMapping": "{\n  \"blog\": \"{{agentLoopEndNode_399.output.finalResponse}}\"\n}"
      }
    }
  }
];

export const edges = [
  {
    "id": "triggerNode_1-agentNode_901",
    "source": "triggerNode_1",
    "target": "agentNode_901",
    "type": "defaultEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "agentNode_901-webSearchNode_683",
    "source": "agentNode_901",
    "target": "webSearchNode_683",
    "type": "conditionEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "data": {
      "condition": "Researcher",
      "invisible": false
    }
  },
  {
    "id": "agentNode_901-LLMNode_814",
    "source": "agentNode_901",
    "target": "LLMNode_814",
    "type": "conditionEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "data": {
      "condition": "Writer",
      "invisible": false
    }
  },
  {
    "id": "agentNode_901-LLMNode_882",
    "source": "agentNode_901",
    "target": "LLMNode_882",
    "type": "conditionEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "data": {
      "condition": "Editor",
      "invisible": false
    }
  },
  {
    "id": "agentNode_901-agentLoopEndNode_399",
    "source": "agentNode_901",
    "target": "agentLoopEndNode_399",
    "type": "agentLoopEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "data": {
      "condition": "Agent Loop End",
      "invisible": true
    }
  },
  {
    "id": "codeNode_604-agentLoopEndNode_399",
    "source": "codeNode_604",
    "target": "agentLoopEndNode_399",
    "type": "defaultEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "LLMNode_814-agentLoopEndNode_399",
    "source": "LLMNode_814",
    "target": "agentLoopEndNode_399",
    "type": "defaultEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "LLMNode_882-agentLoopEndNode_399",
    "source": "LLMNode_882",
    "target": "agentLoopEndNode_399",
    "type": "defaultEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "agentLoopEndNode_399-agentNode_901",
    "source": "agentLoopEndNode_399",
    "target": "agentNode_901",
    "type": "agentLoopEdge",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "data": {
      "condition": "Agent Loop End",
      "invisible": false
    }
  },
  {
    "id": "webSearchNode_683-codeNode_317",
    "source": "webSearchNode_683",
    "target": "codeNode_317",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "codeNode_317-scraperNode_331",
    "source": "codeNode_317",
    "target": "scraperNode_331",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "scraperNode_331-codeNode_604",
    "source": "scraperNode_331",
    "target": "codeNode_604",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "agentLoopEndNode_399-graphqlResponseNode_937",
    "source": "agentLoopEndNode_399",
    "target": "graphqlResponseNode_937",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "response-graphqlResponseNode_937",
    "source": "triggerNode_1",
    "target": "graphqlResponseNode_937",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger",
    "type": "responseEdge"
  }
];

export default { meta, inputs, references, nodes, edges };
