/*
 * # 1A. Embedded Search - PDF Indexation
 * This flow ingests a PDF from a supplied URL, converts it into searchable vector embeddings, and writes those embeddings into the configured vector database as the PDF ingestion path in the wider Embedded Search system.
 *
 * ## Purpose
 * This flow is responsible for turning a single PDF resource into indexed vector data that can be searched later by the kit’s retrieval flow. It solves the ingestion side of the problem for document-based knowledge sources: given a PDF title and URL, it extracts the document text, breaks that text into manageable chunks, embeds those chunks with a configured embedding model, and stores both vectors and metadata in a vector database.
 *
 * The outcome is a durable search index entry for the PDF, keyed by document metadata and prepared for semantic retrieval. That matters because the broader agent pipeline depends on pre-indexed content before it can return grounded search results in the embedded search experience. Without this flow, uploaded PDFs remain opaque files instead of retrievable knowledge assets.
 *
 * Within the broader multi-flow system, this is an entry-point ingestion flow. It sits before retrieval in the overall ingest-search-delete lifecycle described by the parent agent. Its job is not to answer user queries or synthesize responses, but to populate the vector store that downstream search experiences depend on. In practical terms, this flow feeds the retrieval layer by preparing document chunks and metadata in the format expected by the vector database.
 *
 * ## When To Use
 * - Use when a PDF document has been uploaded or made accessible by URL and must become searchable in the embedded search index.
 * - Use when an operator or application wants to add a new document resource to the vector store.
 * - Use when the source content is a PDF, not a website, and semantic search over the document contents is required.
 * - Use when the system already has access to a valid embedding model and vector database configuration.
 * - Use when you need indexed metadata tied to a document `title` and `source` URL for later retrieval or management.
 *
 * ## When Not To Use
 * - Do not use when the source content is a website or web page; the website indexation flow is the correct sibling flow.
 * - Do not use when the goal is to search across already indexed content; the search flow should handle retrieval.
 * - Do not use when the goal is to remove a previously indexed document; the resource deletion flow is the correct choice.
 * - Do not use when the input is a local file blob or binary payload that is not reachable via a resolvable `url`, because this flow reads from `{{triggerNode_1.output.url}}`.
 * - Do not use when the embedding model or vector database has not been configured, because the flow cannot complete indexing without both.
 * - Do not use when the PDF is password-protected and requires credentials, since the file extraction node has an empty `password` setting.
 * - Do not use when you need custom document identifiers beyond `title` as the primary key, because this flow is configured to index using `title`.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `title` | `string` | Yes | Human-readable document title used as metadata and as the vector index primary key. |
 * | `url` | `string` | Yes | Publicly reachable URL of the PDF file to extract, chunk, embed, and index. |
 * | `embeddingModelName` | `model` | Yes | Embedding model selection used by the `Vectorize` node to convert chunks into vectors. |
 * | `vectorDB` | `select` | Yes | Target vector database where vectors and metadata will be written by the `Index` node. |
 *
 * The trigger payload must provide `title` and `url`, and the flow configuration must provide `embeddingModelName` and `vectorDB`. The `url` is expected to resolve to a PDF document. The flow is configured with PDF extraction format, so non-PDF resources are likely to fail or produce unusable results. No explicit max length or language constraint is declared, but very large PDFs will produce more chunks and embeddings, which increases latency and indexing cost.
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `status` | `object` | Raw output returned by the `Index` node after attempting to write vectors and metadata to the configured vector database. |
 *
 * The API response is a structured JSON object with a single top-level field, `status`. That field contains whatever the vector database indexing node returns for the write operation. It is not a human-readable summary generated by the flow; it is the indexing result itself, so its exact shape may vary by configured vector database connector.
 *
 * ## Dependencies
 * ### Upstream Flows
 * - None. This is a standalone entry-point ingestion flow invoked directly through an API or GraphQL request.
 * - Operationally, it assumes the application or operator tooling has already uploaded or otherwise prepared a PDF at a reachable `url`, but no Lamatic flow is required to run immediately before it.
 *
 * ### Downstream Flows
 * - `Embedded Search` retrieval/search flow consumes the indexed vectors and metadata written by this flow. It does not call this flow’s API response directly; instead, it depends on the persisted vector records created from `vectorsField` and `metadataField` in the configured vector database.
 * - Resource lifecycle and operator tooling may also rely indirectly on the indexed document metadata, especially the stored `title` and `source`, for management or deletion workflows.
 *
 * ### External Services
 * - Embedding model provider — generates vector embeddings from text chunks — credential depends on the selected `embeddingModelName` provider configured in Lamatic.
 * - Vector database — stores vectors plus metadata for later similarity search — credential depends on the selected `vectorDB` connector configured in Lamatic.
 * - Remote file host — serves the source PDF at the provided `url` — no dedicated flow credential is defined here, but the URL must be accessible to the extraction node.
 * - Lamatic GraphQL/API layer — receives the trigger request and returns the response — uses the deployment’s Lamatic API configuration.
 *
 * ### Environment Variables
 * - `LAMATIC_API_URL` — Lamatic API endpoint used by the deployed application to invoke this flow — used outside the flow runtime at invocation time.
 * - `LAMATIC_PROJECT_ID` — Lamatic project identifier used to route API calls to the correct deployed project — used outside the flow runtime at invocation time.
 * - `LAMATIC_API_KEY` — authentication credential for invoking Lamatic APIs — used outside the flow runtime at invocation time.
 * - Provider-specific embedding credentials — authenticate the selected embedding model for `Vectorize` — used by the `Vectorize` node through Lamatic-managed model configuration.
 * - Vector database credentials — authenticate writes to the selected index backend for `Index` — used by the `Index` node through Lamatic-managed database configuration.
 *
 * ## Node Walkthrough
 * 1. `API Request` (trigger node) receives the invocation payload for this flow. In practice, that payload must include `title` and `url`, where `url` points to the PDF that should be indexed.
 * 2. `Variables` (variables node) maps the incoming trigger fields into normalized internal variables. It creates `title` from `{{triggerNode_1.output.title}}` and `source` from `{{triggerNode_1.output.url}}`, establishing the base metadata carried through later indexing steps.
 * 3. `Extract from File` (extract-from-file node) fetches the file from `{{triggerNode_1.output.url}}` and parses it as `pdf`. It is configured to join pages, so the extracted output is treated as a continuous document stream rather than isolated page fragments.
 * 4. `Extract Text` (code node) runs the referenced extraction script to turn the file extraction output into clean text suitable for chunking. This is the point where the flow normalizes extracted PDF content into a plain-text representation.
 * 5. `Chunking` (chunk node) splits the extracted text into recursive character-based chunks using separators `\n\n`, `\n`, and space. It targets chunks of `500` characters with `50` characters of overlap to preserve context across chunk boundaries for retrieval quality.
 * 6. `Get Chunks` (code node) runs the referenced script that collects and reshapes the chunking output into the exact list of text segments expected by the embedding stage. This node effectively bridges the chunking format into vectorization-ready input.
 * 7. `Vectorize` (vectorize node) sends the prepared chunk list to the selected `embeddingModelName` and generates embeddings. Its input text comes from `{{codeNode_254.output}}`, and its output exposes the vector array used for indexing.
 * 8. `Transform Metadata` (code node) runs the referenced metadata transformation script to prepare `metadata` aligned with the vectors. This metadata is based on the flow’s normalized variables, especially `title` and `source`, and is shaped for the target vector database write.
 * 9. `Index` (index node) writes the vectors and metadata into the selected `vectorDB`. It uses `title` as the primary key and is configured with `duplicateOperation` set to `overwrite`, meaning a new indexing run for the same `title` replaces the prior indexed record rather than creating a duplicate.
 * 10. `API Response` (response node) returns a JSON response with `status` mapped from `{{IndexNode_622.output}}`, exposing the outcome of the indexing operation to the caller.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | Flow fails before vectorization starts | `url` is missing, malformed, unreachable, or does not point to a valid PDF | Verify the trigger payload contains a publicly reachable PDF `url` and test that the file can be fetched by the Lamatic runtime. |
 * | File extraction returns empty or unusable text | The PDF is image-only, corrupted, encrypted, or poorly formatted for text extraction | Use OCR before ingestion, upload a text-based PDF, or provide a non-encrypted source document. |
 * | `Vectorize` node fails with authorization or model errors | `embeddingModelName` is not configured correctly or provider credentials are missing | Configure a valid embedding model in the flow inputs and ensure the corresponding provider credentials are available in Lamatic. |
 * | `Index` node fails with connection or authentication errors | `vectorDB` is not configured or its credentials are missing/invalid | Select a valid vector database connection and verify its credentials and index configuration in Lamatic. |
 * | Search later returns no results for the document | Indexing wrote no vectors because text extraction or chunk generation produced empty output | Inspect outputs from `Extract Text`, `Chunking`, and `Get Chunks` to confirm non-empty text segments are being passed to `Vectorize`. |
 * | Existing document appears replaced unexpectedly | `duplicateOperation` is set to `overwrite` and `title` is used as the primary key | Use unique `title` values per document or change key strategy if multiple versions must coexist. |
 * | Flow responds with an unexpected `status` shape | The response mirrors the raw `Index` connector output, which can vary by vector database implementation | Inspect the configured vector DB connector’s response contract and normalize it at the caller if a stable schema is required. |
 * | Invocation from the application fails before the flow runs | Lamatic API credentials such as `LAMATIC_API_URL`, `LAMATIC_PROJECT_ID`, or `LAMATIC_API_KEY` are missing in the calling environment | Set the required Lamatic environment variables in local and deployed environments, then retry the request. |
 * | A caller expects upstream flow output but nothing is available | This flow is an entry-point flow and does not consume another flow’s runtime output | Invoke it directly with the required trigger payload instead of trying to chain from a nonexistent upstream ingestion step. |
 *
 * ## Notes
 * - The flow’s metadata description is empty in source, so operational intent should be inferred from the node graph and kit documentation rather than the flow `description` field.
 * - The sample test input uses a Supabase-hosted PDF URL, which suggests the common operating pattern is to upload files to object storage first, then pass their public URL into this flow.
 * - Because `joinPages` is enabled during extraction, page boundaries may be softened before chunking. That is helpful for continuity but may reduce page-level traceability unless the referenced scripts explicitly preserve it.
 * - Chunking is character-based rather than token-based. Retrieval quality and embedding cost may need tuning if your PDFs are unusually dense, multilingual, or structurally complex.
 * - Metadata written to the vector store is produced by a custom script, so any downstream assumptions about field names beyond `title` and `source` should be validated against that script’s implementation.
 * - Since `title` is the declared primary key, title collisions across distinct documents can overwrite prior records. This is important for operators building multi-tenant or versioned indexing workflows.
 */

// Flow: embedded-search-pdf-indexation

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "1A. Embedded Search - PDF Indexation",
  "description": "",
  "tags": [],
  "testInput": {
    "title": "Sample Resume",
    "url": "https://aseskssykbhhiborrwws.supabase.co/storage/v1/object/public/alpha/DhruvP_Resume.pdf"
  },
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": ""
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {
  "vectorizeNode_639": [
    {
      "name": "embeddingModelName",
      "label": "Embedding Model Name",
      "type": "model",
      "mode": "embedding",
      "description": "Select the model to convert the texts into vector representations.",
      "modelType": "embedder/text",
      "required": true,
      "isPrivate": true,
      "defaultValue": "",
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      }
    }
  ],
  "IndexNode_622": [
    {
      "name": "vectorDB",
      "label": "Vector DB",
      "type": "select",
      "isDB": true,
      "required": true,
      "isPrivate": true,
      "defaultValue": "",
      "description": "Select the vector database where the vectors will be indexed."
    }
  ]
};

// ── References ────────────────────────────────────────
// Cross-references to extracted resources in their own directories
// NOTE: Trigger widget settings are saved to triggers/widgets/ but NOT cross-referenced here
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "scripts": {
    "embedded_search_pdf_indexation_extract_text": "@scripts/embedded-search-pdf-indexation_extract-text.ts",
    "embedded_search_pdf_indexation_get_chunks": "@scripts/embedded-search-pdf-indexation_get-chunks.ts",
    "embedded_search_pdf_indexation_transform_metadata": "@scripts/embedded-search-pdf-indexation_transform-metadata.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "extractFromFileNode_944",
    "data": {
      "nodeId": "extractFromFileNode",
      "values": {
        "id": "extractFromFileNode_944",
        "trim": false,
        "ltrim": false,
        "quote": "\"",
        "rtrim": false,
        "format": "pdf",
        "comment": "null",
        "fileUrl": "{{triggerNode_1.output.url}}",
        "headers": true,
        "maxRows": "0",
        "encoding": "utf8",
        "nodeName": "Extract from File",
        "password": "",
        "skipRows": "0",
        "delimiter": ",",
        "joinPages": true,
        "ignoreEmpty": false,
        "returnRawText": false,
        "encodeAsBase64": false,
        "discardUnmappedColumns": false
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 300
    },
    "selected": false,
    "draggable": false
  },
  {
    "id": "codeNode_315",
    "data": {
      "nodeId": "codeNode",
      "values": {
        "id": "codeNode_315",
        "code": "@scripts/embedded-search-pdf-indexation_extract-text.ts",
        "nodeName": "Extract Text"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 450
    },
    "selected": false,
    "draggable": false
  },
  {
    "id": "chunkNode_318",
    "data": {
      "nodeId": "chunkNode",
      "values": {
        "id": "chunkNode_318",
        "nodeName": "Chunking",
        "chunkField": "{{codeNode_315.output}}",
        "numOfChars": 500,
        "separators": [
          "\n\n",
          "\n",
          " "
        ],
        "chunkingType": "recursiveCharacterTextSplitter",
        "overlapChars": 50
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 600
    },
    "selected": false,
    "draggable": false
  },
  {
    "id": "codeNode_254",
    "data": {
      "nodeId": "codeNode",
      "values": {
        "id": "codeNode_254",
        "code": "@scripts/embedded-search-pdf-indexation_get-chunks.ts",
        "nodeName": "Get Chunks"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 750
    },
    "selected": false,
    "draggable": false
  },
  {
    "id": "vectorizeNode_639",
    "data": {
      "nodeId": "vectorizeNode",
      "values": {
        "id": "vectorizeNode_639",
        "nodeName": "Vectorize",
        "inputText": "{{codeNode_254.output}}",
        "embeddingModelName": ""
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 900
    },
    "selected": false,
    "draggable": false
  },
  {
    "id": "codeNode_507",
    "data": {
      "nodeId": "codeNode",
      "values": {
        "id": "codeNode_507",
        "code": "@scripts/embedded-search-pdf-indexation_transform-metadata.ts",
        "nodeName": "Transform Metadata"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 1050
    },
    "selected": false,
    "draggable": false
  },
  {
    "id": "IndexNode_622",
    "data": {
      "nodeId": "IndexNode",
      "values": {
        "id": "IndexNode_622",
        "nodeName": "Index",
        "vectorDB": "",
        "primaryKeys": [
          "title"
        ],
        "vectorsField": "{{vectorizeNode_639.output.vectors}}",
        "metadataField": "{{codeNode_507.output.metadata}}",
        "duplicateOperation": "overwrite"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 1200
    },
    "selected": false,
    "draggable": false
  },
  {
    "id": "variablesNode_954",
    "data": {
      "nodeId": "variablesNode",
      "values": {
        "id": "variablesNode_954",
        "mapping": "{\n  \"title\": {\n    \"type\": \"string\",\n    \"value\": \"{{triggerNode_1.output.title}}\"\n  },\n  \"source\": {\n    \"type\": \"string\",\n    \"value\": \"{{triggerNode_1.output.url}}\"\n  }\n}",
        "nodeName": "Variables"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 150
    },
    "selected": false,
    "draggable": false
  },
  {
    "id": "triggerNode_1",
    "data": {
      "modes": {},
      "nodeId": "graphqlNode",
      "values": {
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": ""
      },
      "trigger": true
    },
    "type": "triggerNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 0
    },
    "selected": false
  },
  {
    "id": "responseNode_triggerNode_1",
    "data": {
      "label": "Response",
      "nodeId": "graphqlResponseNode",
      "values": {
        "headers": "{\"content-type\":\"application/json\"}",
        "retries": "0",
        "nodeName": "API Response",
        "webhookUrl": "",
        "retry_delay": "0",
        "outputMapping": "{\n  \"status\": \"{{IndexNode_622.output}}\"\n}"
      },
      "isResponseNode": true
    },
    "type": "responseNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 1350
    },
    "selected": false
  }
];

export const edges = [
  {
    "id": "variablesNode_954-extractFromFileNode_944",
    "type": "defaultEdge",
    "source": "variablesNode_954",
    "target": "extractFromFileNode_944",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "extractFromFileNode_944-codeNode_315",
    "type": "defaultEdge",
    "source": "extractFromFileNode_944",
    "target": "codeNode_315",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "codeNode_315-chunkNode_318",
    "type": "defaultEdge",
    "source": "codeNode_315",
    "target": "chunkNode_318",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "chunkNode_318-codeNode_254",
    "type": "defaultEdge",
    "source": "chunkNode_318",
    "target": "codeNode_254",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "codeNode_254-vectorizeNode_639",
    "type": "defaultEdge",
    "source": "codeNode_254",
    "target": "vectorizeNode_639",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "vectorizeNode_639-codeNode_507",
    "type": "defaultEdge",
    "source": "vectorizeNode_639",
    "target": "codeNode_507",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "codeNode_507-IndexNode_622",
    "type": "defaultEdge",
    "source": "codeNode_507",
    "target": "IndexNode_622",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "triggerNode_1-variablesNode_954",
    "type": "defaultEdge",
    "source": "triggerNode_1",
    "target": "variablesNode_954",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "IndexNode_622-responseNode_triggerNode_1",
    "type": "defaultEdge",
    "source": "IndexNode_622",
    "target": "responseNode_triggerNode_1",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "response-trigger_triggerNode_1",
    "type": "responseEdge",
    "source": "triggerNode_1",
    "target": "responseNode_triggerNode_1",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger"
  }
];

export default { meta, inputs, references, nodes, edges };
