/*
 * # JSON Summariser
 * A flow that accepts a JSON file URL, extracts its contents, and returns an LLM-generated summary as the API-facing entry point for this agent kit.
 *
 * ## Purpose
 * This flow is responsible for turning raw JSON available at a caller-provided URL into a concise, human-readable summary. It solves the narrow but common sub-task of making large, nested, or unfamiliar JSON payloads understandable without requiring the caller to inspect the raw structure manually. In practice, this is useful when JSON comes from API responses, exports, logs, or third-party systems and a quick interpretation is more valuable than schema-level parsing.
 *
 * The flow produces a single summary string that captures the key information in the source JSON while aiming to preserve the essential details. That output matters because it gives downstream humans or systems a compact representation of the document that can be displayed directly, logged, reviewed in support workflows, or passed into later decision-making steps without carrying the full raw payload.
 *
 * Within the broader agent pipeline, this flow sits at the ingest-and-synthesize boundary. It is an entry-point flow invoked directly through an API request, performs retrieval by fetching the file from the supplied `url`, then performs synthesis by running an LLM summarization prompt over the extracted content. In the parent kit, it is effectively the full pipeline for this use case rather than one stage in a multi-flow chain.
 *
 * ## When To Use
 * - Use when an external caller has a `url` pointing to a JSON document and needs a fast, readable summary rather than the raw file contents.
 * - Use when the source data is machine-generated JSON from an API, export, log bundle, or third-party service and a human operator needs the main points extracted.
 * - Use when you want a lightweight API-accessible summarization step that can be embedded in support tooling, dashboards, or internal analysis workflows.
 * - Use when there is no need for schema-specific parsing, transformation, or validation beyond fetching the file and summarizing its contents.
 * - Use when this kit is being invoked as a standalone utility flow from an external system over the GraphQL/API boundary.
 *
 * ## When Not To Use
 * - Do not use when the input is not a URL-accessible file, since this flow expects the trigger payload to provide `url` and the extraction node fetches content from that location.
 * - Do not use when the source content is not actually JSON or cannot be interpreted meaningfully by the extraction step.
 * - Do not use when you need structured field extraction, validation against a schema, or deterministic transformation instead of a prose summary.
 * - Do not use when the file requires access methods not available to the runtime, such as private network reachability or authentication that has not been configured.
 * - Do not use when another flow in your environment is responsible for direct document QA, indexing, search, or multi-step reasoning over the source data rather than summarization.
 * - Do not use when callers need the raw extracted JSON returned to them, because this flow returns only the generated summary in its API response.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `url` | `string` | Yes | Publicly accessible or otherwise retrievable URL pointing to the JSON file to summarize. |
 *
 * The trigger definition does not declare private inputs, but the runtime behavior clearly assumes the incoming API request includes `url` at `triggerNode_1.output.url`. The URL should resolve to content the extraction node can fetch successfully. Although the node is labeled `Extract from File`, the template description and parent agent context indicate the intended source is JSON delivered from a URL. If the resource is inaccessible, malformed, or unexpectedly formatted, the flow will fail or produce poor summaries.
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `output` | `string` | Concise natural-language summary generated from the extracted JSON content. |
 *
 * The API response is a single-field object containing `output`. The value is prose, not structured JSON, and is generated by the LLM based on the extracted source content and system prompt. Completeness depends on source size, extraction quality, and model behavior; very large or unusually complex JSON may be summarized at a higher level rather than exhaustively.
 *
 * ## Dependencies
 * ### Upstream Flows
 * - None. This is a standalone entry-point flow invoked directly by an external caller through the `API Request` trigger.
 * - The only prerequisite is that the invoker supplies a valid `url` in the trigger request payload.
 *
 * ### Downstream Flows
 * - None are defined in this kit.
 * - The returned `output` field is intended for direct consumption by external applications, operators, dashboards, or orchestration layers rather than an internal downstream Lamatic flow.
 *
 * ### External Services
 * - GraphQL/API runtime — receives the incoming request and returns the final response — required credentials depend on the deployment hosting the `graphqlNode` and `graphqlResponseNode`
 * - Remote file hosting or HTTP endpoint — serves the JSON document referenced by `url` — any access requirements are determined by the target URL and runtime network permissions
 * - Configured LLM model from `@model-configs/json-summariser_generate-text.ts` — generates the summary from extracted content — required model credential depends on the provider configured in the model config
 *
 * ### Environment Variables
 * - No flow-specific environment variables are declared in the exported flow source.
 * - Model provider credentials may still be required by the LLM configuration referenced by `@model-configs/json-summariser_generate-text.ts`, but they are not named in this flow definition.
 * - Deployment-level API credentials or connector settings may also be required by the GraphQL runtime or model provider, but they are not explicitly exposed in this flow file.
 *
 * ## Node Walkthrough
 * 1. `API Request` (`triggerNode` / `graphqlNode`) receives the incoming API call and exposes request fields to the flow runtime. For this flow, the critical value is `url`, which is expected to contain the location of the JSON file to summarize.
 *
 * 2. `Extract from File` (`dynamicNode` / `extractFromFileNode`) fetches the file located at `{{triggerNode_1.output.url}}` and extracts its contents for downstream use. In this flow, it is the retrieval stage: it turns a caller-supplied file URL into content the summarizer can read. The node is configured to work from the remote file URL, keeps trimming options disabled, and does not return raw text as a base64 blob. Although one config field shows `format` as `pdf`, the documented intent of the template is JSON summarization, so the operational expectation is that this node retrieves and exposes the JSON content or a text representation of it for the model.
 *
 * 3. `Generate Text` (`dynamicNode` / `LLMNode`) takes the extracted content and sends it to the configured LLM along with the system prompt referenced by `@prompts/json-summariser_generate-text_system.md`. This is the synthesis step. Its purpose is to identify the key information in the JSON and produce a concise summary rather than echoing the full source. The exact model, message configuration, and memory settings come from `@model-configs/json-summariser_generate-text.ts`.
 *
 * 4. `API Response` (`dynamicNode` / `graphqlResponseNode`) maps `{{LLMNode_306.output.generatedResponse}}` into the API response field `output` and returns it to the caller. This final step defines the public contract of the flow: callers receive one summary string rather than the intermediate extracted content.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | Request fails before summarization starts | Missing or malformed `url` in the incoming trigger payload | Ensure the API caller sends a valid `url` string in the request variables or body expected by the deployed GraphQL endpoint. |
 * | Extraction step returns no useful content | The `url` is unreachable, expired, blocked, or does not return the expected file | Verify the URL is correct, publicly accessible or reachable from the Lamatic runtime, and returns the intended JSON document. |
 * | Summary is empty or unhelpfully generic | Source file is empty, extraction produced little usable text, or the content is not valid JSON-like material | Inspect the source file directly, confirm it contains meaningful JSON, and test the extraction node against a known-good sample URL. |
 * | Flow errors during model execution | LLM provider credentials or model configuration are missing or invalid | Check the provider setup used by `@model-configs/json-summariser_generate-text.ts` and ensure the required deployment secrets are configured. |
 * | Returned summary omits important details | Source JSON is too large, deeply nested, or noisy for a single-pass concise summary | Reduce the input size, preprocess the JSON externally, or adjust the prompt/model configuration to target the fields or sections that matter most. |
 * | Caller expects structured JSON output but receives plain text | The response contract only maps the LLM's `generatedResponse` into `output` | Update client expectations or modify the flow to produce structured output if that is required by the consuming system. |
 * | Invocation is attempted as though another flow should have prepared data first | Misunderstanding of kit architecture; this flow is the entry point and has no upstream Lamatic dependency | Call this flow directly with the required `url` rather than waiting for a prior internal flow to populate inputs. |
 * | Extraction behavior seems inconsistent with JSON intent | The extraction node configuration includes values that do not perfectly reflect the template description, such as `format` set to `pdf` | Validate the node behavior in your workspace with representative JSON URLs and adjust the extraction configuration if your deployment requires stricter JSON handling. |
 *
 * ## Notes
 * - This template is operationally simple: fetch, summarize, return. That makes it easy to integrate, but it also means there is no built-in branch logic, schema awareness, or fallback handling.
 * - The flow has no declared private `inputs`, so most runtime sensitivity comes from the incoming `url` and the external LLM configuration rather than from per-flow secrets defined in the source.
 * - There is a notable mismatch between the documented purpose of the flow as a JSON summarizer and one extraction-node setting that lists `format` as `pdf`. Treat the documented behavior and end-to-end tests in your environment as authoritative, and verify extraction against real JSON sources before relying on the flow in production.
 * - Because the final response contains only summarized prose, this flow is best suited for comprehension and triage, not for compliance-grade extraction or deterministic data processing.
 */

// Flow: json-summariser

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "JSON Summariser",
  "description": "This workflow builds a JSON summarization system. It takes a URL of a JSON file as input, processes the data using a Generate Text node, and produces a concise summary of the key information, enabling efficient data analysis and easier extraction of insights from complex JSON structures.",
  "tags": [
    "📞 Support",
    "🌱 Growth"
  ],
  "testInput": null,
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": "https://studio.lamatic.ai/template/json-summariser",
  "author": {
    "name": "Naitik Kapadia",
    "email": "naitikk@lamatic.ai"
  }
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {};

// ── References ────────────────────────────────────────
// Cross-references to extracted resources in their own directories
// NOTE: Trigger widget settings are saved to triggers/widgets/ but NOT cross-referenced here
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "json_summariser_generate_text_system": "@prompts/json-summariser_generate-text_system.md"
  },
  "modelConfigs": {
    "json_summariser_generate_text": "@model-configs/json-summariser_generate-text.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "type": "triggerNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlNode",
      "trigger": true,
      "values": {
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": ""
      }
    }
  },
  {
    "id": "extractFromFileNode_674",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "extractFromFileNode",
      "values": {
        "nodeName": "Extract from File",
        "trim": false,
        "ltrim": false,
        "quote": "\"",
        "rtrim": false,
        "format": "pdf",
        "comment": "null",
        "fileUrl": "{{triggerNode_1.output.url}}",
        "headers": true,
        "maxRows": "0",
        "encoding": "utf8",
        "password": "",
        "skipRows": "0",
        "delimiter": ",",
        "joinPages": true,
        "ignoreEmpty": false,
        "returnRawText": false,
        "encodeAsBase64": false,
        "discardUnmappedColumns": false
      }
    }
  },
  {
    "id": "LLMNode_306",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "LLMNode",
      "values": {
        "nodeName": "Generate Text",
        "tools": [],
        "prompts": [
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/json-summariser_generate-text_system.md"
          }
        ],
        "memories": "@model-configs/json-summariser_generate-text.ts",
        "messages": "@model-configs/json-summariser_generate-text.ts",
        "generativeModelName": "@model-configs/json-summariser_generate-text.ts"
      }
    }
  },
  {
    "id": "graphqlResponseNode_153",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlResponseNode",
      "values": {
        "nodeName": "API Response",
        "outputMapping": "{\n  \"output\": \"{{LLMNode_306.output.generatedResponse}}\"\n}"
      }
    }
  }
];

export const edges = [
  {
    "id": "triggerNode_1-extractFromFileNode_674",
    "source": "triggerNode_1",
    "target": "extractFromFileNode_674",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "extractFromFileNode_674-LLMNode_306",
    "source": "extractFromFileNode_674",
    "target": "LLMNode_306",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "LLMNode_306-graphqlResponseNode_153",
    "source": "LLMNode_306",
    "target": "graphqlResponseNode_153",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "response-graphqlResponseNode_153",
    "source": "triggerNode_1",
    "target": "graphqlResponseNode_153",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger",
    "type": "responseEdge"
  }
];

export default { meta, inputs, references, nodes, edges };
