/*
 * # Chatbot Widget - Assistant Bot
 * A chat-widget RAG flow that answers end-user questions against the bundle’s indexed document corpus and serves as the interactive consumption layer of the wider document parsing system.
 *
 * ## Purpose
 * This flow is responsible for the question-answering side of the Document Parsing kit. After documents have been ingested, chunked, embedded, and written into a vector database by the sibling ingestion pipeline, this flow accepts a chat message from an embedded widget, retrieves relevant indexed context, and generates a grounded answer for the user. Its job is not to parse or index documents, but to turn the indexed knowledge base into a usable conversational experience.
 *
 * The outcome is a single chat response returned to the widget user. That response is generated by a retrieval-augmented generation step that combines semantic search over the configured vector store with a chat model and project prompts. This matters because the overall agent pipeline only becomes useful to end-users once indexed content can be queried reliably and presented in natural language.
 *
 * In the broader chain described by the parent agent, this flow sits in the retrieve-and-synthesize stage. The `document-parsing-etl` flow prepares the searchable knowledge state upstream; this flow then receives a user question, retrieves semantically relevant material from that state, and synthesizes an answer suitable for a widget conversation. It is therefore the downstream consumer of the ingestion/indexing flow and the primary interactive interface exposed to end-users.
 *
 * ## When To Use
 * - Use when an end-user submits a message through the embedded `Chat Widget` interface.
 * - Use when documents have already been ingested into a vector database and you want conversational answers grounded in that indexed corpus.
 * - Use when the query should be answered from private or curated document knowledge rather than from general model knowledge alone.
 * - Use when you need a lightweight retrieval-and-response layer on top of the document parsing kit without re-running ingestion.
 * - Use when the application needs a user-facing assistant response in a chat UI rather than a structured extraction or indexing output.
 *
 * ## When Not To Use
 * - Do not use when documents have not yet been processed and indexed; run the upstream `document-parsing-etl` flow first.
 * - Do not use for initial document ingestion, chunking, metadata extraction, or vector indexing; that is handled by the sibling ingestion flow.
 * - Do not use when the incoming payload is a file, URL, or raw document to be parsed instead of a natural-language chat question.
 * - Do not use when no vector database has been configured for `RAGNode_711`, because retrieval cannot execute without a target store.
 * - Do not use when you need deterministic structured JSON extraction from documents rather than a prose answer.
 * - Do not use when a non-widget invocation path is required and the system expects an API-style backend trigger rather than the chat widget trigger configured here.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `chatMessage` | `string` | Yes | The end-user’s message text received from the `Chat Widget` trigger and used as the retrieval query. |
 *
 * Below the table, describe any notable input constraints or validation assumptions (e.g. max length, expected format, language).
 *
 * The flow source explicitly references `{{triggerNode_1.output.chatMessage}}` as the query input to retrieval, so a usable text message is assumed to be present on the trigger output. The flow is designed for natural-language questions or requests suitable for semantic retrieval. No explicit maximum length, schema validation, language restriction, or sanitization logic is defined in the flow itself, so callers should assume standard widget-side validation is responsible for rejecting empty or malformed submissions.
 *
 * In addition to trigger-time user input, the flow also requires private configuration on `RAGNode_711` before it can run successfully:
 * - `vectorDB` — the vector database/index to query
 * - `embeddingModelName` — the embedding model used to embed the query
 * - `generativeModelName` — the chat/generative model used to compose the answer
 *
 * These are configuration inputs rather than end-user payload fields, but they are mandatory for operational use.
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `content` | `string` | The final assistant reply returned by the `Chat Response` node, sourced from `RAGNode_711.output.modelResponse`. |
 *
 * The API response is a single prose chat message rather than a structured object of extracted fields. Internally, the RAG node may produce retrieval artifacts and intermediate values, but this flow exposes only the generated answer text to the caller through the response node. Completeness depends on the quality and availability of indexed documents, retrieval match quality, and model behavior; if retrieval is weak or empty, the answer may be incomplete, generic, or fail depending on runtime handling.
 *
 * ## Dependencies
 * ### Upstream Flows
 * - `document-parsing-etl` — must have already ingested source documents, generated embeddings/chunks, and written them into the vector database selected by `RAGNode_711`.
 *   - Required upstream outcome: a populated vector index containing the document corpus this assistant should search.
 *   - Consumed downstream by this flow as: semantic retrieval context from the configured `vectorDB`.
 * - As an execution entry point, this flow is triggered directly by the widget and does not require another flow to invoke it synchronously at runtime. Its data dependency is on prior indexing having completed successfully.
 *
 * ### Downstream Flows
 * - No downstream Lamatic flow is shown as consuming this flow’s output.
 * - The primary consumer is the chat widget client, which uses the response field `content` to render the assistant message back to the end-user.
 *
 * ### External Services
 * - Chat widget trigger service — receives end-user messages from the embedded widget and starts the flow — credential/environment requirement is defined by Lamatic widget deployment configuration.
 * - Vector database selected by `vectorDB` — stores and serves document embeddings for semantic retrieval — required credential depends on the specific database connector configured in Lamatic.
 * - Embedding model selected by `embeddingModelName` — converts the incoming user query into vector space for retrieval — required credential depends on the configured model provider.
 * - Generative chat model selected by `generativeModelName` — generates the final answer from retrieved context and prompts — required credential depends on the configured model provider.
 *
 * ### Environment Variables
 * - No explicit environment variables are declared in the flow source.
 * - Provider-specific credentials or connector settings may still be required by the selected vector database, embedding model, generative model, or widget deployment, but they are not named in this flow definition.
 *
 * ## Node Walkthrough
 * 1. `Chat Widget` (`triggerNode`) starts the flow when an end-user sends a message through the configured widget. The node provides the runtime chat payload, and the flow specifically uses the trigger output field `chatMessage` as the user query. The widget domain and chat configuration are referenced from `@triggers/widgets/chatbot-widget_chat-widget.ts`.
 *
 * 2. `Variables` (`dynamicNode`) defines a runtime variable named `instructions` with the value `always give answer in a funny and quirky tone`. In this flow definition, that variable is created before retrieval/generation, but there is no explicit field mapping showing it being injected into the `RAG` node prompts or settings. It should therefore be treated as available flow context, with practical effect dependent on Lamatic runtime behavior outside the visible source.
 *
 * 3. `RAG` (`dynamicNode`) performs the core retrieval-augmented generation step. It takes the user query from `{{triggerNode_1.output.chatMessage}}`, embeds it using the configured `embeddingModelName`, searches the configured `vectorDB`, and uses the referenced system and user prompts to compose a grounded response with the configured `generativeModelName`. Additional retrieval and conversation behavior such as `limit`, `certainty`, `messages`, and `memories` are pulled from `@model-configs/chatbot-widget_rag.ts`, so the exact retrieval depth and chat memory policy are defined externally to this flow file.
 *
 * 4. `Chat Response` (`responseNode`) returns `{{RAGNode_711.output.modelResponse}}` to the widget caller as the final assistant message. This is the only explicit response exposed by the flow.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | The flow fails before generating an answer | One or more required private inputs on `RAGNode_711` are missing, especially `vectorDB`, `embeddingModelName`, or `generativeModelName` | Configure all required private inputs in the Lamatic workspace and verify the selected providers are accessible |
 * | The assistant returns a weak, generic, or ungrounded answer | The vector index is empty, contains irrelevant documents, or the upstream ingestion flow has not run successfully | Run or re-run `document-parsing-etl`, verify documents were indexed into the same vector store this flow queries, and confirm embeddings were created correctly |
 * | No useful answer is produced for a valid question | Retrieval returned few or no relevant matches because the query wording, chunking strategy, or retrieval threshold did not align with indexed content | Inspect the external model config referenced by `@model-configs/chatbot-widget_rag.ts`, tune retrieval settings, and verify document chunk quality |
 * | The flow cannot connect to the vector store or model provider | Missing or invalid provider credentials or connector configuration | Recheck provider setup in Lamatic, validate credentials, and ensure the selected resources are available in the target environment |
 * | The widget invocation succeeds but the answer style does not reflect the quirky tone instruction | The `Variables` node sets `instructions`, but the visible flow source does not explicitly inject that variable into the `RAG` prompts | Update the prompts or node mappings so `instructions` is referenced directly, or confirm whether the runtime automatically exposes variables to prompt rendering |
 * | The flow is triggered but errors on query handling | The incoming trigger payload does not include a usable `chatMessage` string | Validate the widget configuration and ensure the trigger emits the expected `chatMessage` field |
 * | Users ask about newly uploaded documents but answers reflect older state | The latest documents were not yet ingested or were written to a different index than the one configured here | Confirm ingestion completion, index destination, and `vectorDB` selection consistency across both flows |
 *
 * ## Notes
 * - The flow metadata description is empty, so operational intent must be inferred from node wiring, prompt references, and the parent kit documentation.
 * - The exact assistant behavior is partly defined outside this file in `@prompts/chatbot-widget_rag_system.md`, `@prompts/chatbot-widget_rag_user.md`, and `@model-configs/chatbot-widget_rag.ts`. For canonical prompt wording, retrieval limits, certainty thresholds, and memory settings, those referenced assets should be treated as part of the effective runtime contract.
 * - The `Chat Response` node does not expose citations, source chunks, or retrieval metadata, even though the underlying RAG step may use them internally. If your application requires source attribution in the UI, the flow will need to be extended.
 * - Because this flow is widget-triggered, it is best suited for synchronous interactive use. Bulk question answering, offline evaluation, or backend batch workloads would usually require a different trigger pattern.
 * - The response edge from the trigger to `Chat Response` indicates this is structurally a trigger-to-response chat flow, but the actual content returned is entirely dependent on successful execution of the `RAG` node.
 */

// Flow: chatbot-widget

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Chatbot Widget - Assistant Bot",
  "description": "",
  "tags": [],
  "testInput": "",
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": ""
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {
  "RAGNode_711": [
    {
      "name": "vectorDB",
      "label": "Database",
      "type": "select",
      "isDB": true,
      "required": true,
      "description": "Select the vector database to be queried.",
      "defaultValue": "",
      "isPrivate": true
    },
    {
      "name": "embeddingModelName",
      "label": "Embedding Model Name",
      "type": "model",
      "mode": "embedding",
      "description": "This field allows the user to select the embedding model used to embed the query into vector space. It loads available embedding models through the listModels method.",
      "modelType": "embedder/text",
      "required": true,
      "isPrivate": true,
      "defaultValue": "",
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      }
    },
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "description": "Select the model to generate responses from the query results.",
      "type": "model",
      "mode": "chat",
      "modelType": "generator/text",
      "required": true,
      "defaultValue": [
        {
          "configName": "configA",
          "type": "generator/text",
          "provider_name": "",
          "credential_name": "",
          "params": {}
        }
      ],
      "isPrivate": true,
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      }
    }
  ]
};

// ── References ────────────────────────────────────────
// Cross-references to extracted resources in their own directories
// NOTE: Trigger widget settings are saved to triggers/widgets/ but NOT cross-referenced here
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "chatbot_widget_rag_system": "@prompts/chatbot-widget_rag_system.md",
    "chatbot_widget_rag_user": "@prompts/chatbot-widget_rag_user.md"
  },
  "modelConfigs": {
    "chatbot_widget_rag": "@model-configs/chatbot-widget_rag.ts"
  },
  "triggers": {
    "chatbot_widget_chat_widget": "@triggers/widgets/chatbot-widget_chat-widget.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "data": {
      "nodeId": "chatTriggerNode",
      "values": {
        "id": "triggerNode_1",
        "chat": "",
        "domains": "@triggers/widgets/chatbot-widget_chat-widget.ts",
        "nodeName": "Chat Widget",
        "chatConfig": "@triggers/widgets/chatbot-widget_chat-widget.ts"
      },
      "trigger": true
    },
    "type": "triggerNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 0
    },
    "selected": false
  },
  {
    "id": "variablesNode_789",
    "data": {
      "label": "dynamicNode node",
      "modes": {},
      "nodeId": "variablesNode",
      "values": {
        "mapping": "{\n  \"instructions\": {\n    \"type\": \"string\",\n    \"value\": \"always give answer in a funny and quirky tone\"\n  }\n}",
        "nodeName": "Variables"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 150
    },
    "selected": false
  },
  {
    "id": "RAGNode_711",
    "data": {
      "label": "dynamicNode node",
      "modes": {},
      "nodeId": "RAGNode",
      "values": {
        "limit": "@model-configs/chatbot-widget_rag.ts",
        "filters": "",
        "prompts": [
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/chatbot-widget_rag_system.md"
          },
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7d",
            "role": "user",
            "content": "@prompts/chatbot-widget_rag_user.md"
          }
        ],
        "memories": "@model-configs/chatbot-widget_rag.ts",
        "messages": "@model-configs/chatbot-widget_rag.ts",
        "nodeName": "RAG",
        "vectorDB": "",
        "certainty": "@model-configs/chatbot-widget_rag.ts",
        "queryField": "{{triggerNode_1.output.chatMessage}}",
        "embeddingModelName": "@model-configs/chatbot-widget_rag.ts",
        "generativeModelName": "@model-configs/chatbot-widget_rag.ts"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 300
    },
    "selected": true
  },
  {
    "id": "chatResponseNode_988",
    "data": {
      "nodeId": "chatResponseNode",
      "values": {
        "id": "chatResponseNode_988",
        "content": "{{RAGNode_711.output.modelResponse}}",
        "nodeName": "Chat Response",
        "references": ""
      }
    },
    "type": "responseNode",
    "measured": {
      "width": 218,
      "height": 95
    },
    "position": {
      "x": 0,
      "y": 450
    },
    "selected": false
  }
];

export const edges = [
  {
    "id": "RAGNode_711-chatResponseNode_988-221",
    "type": "defaultEdge",
    "source": "RAGNode_711",
    "target": "chatResponseNode_988",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "triggerNode_1-variablesNode_789",
    "type": "defaultEdge",
    "source": "triggerNode_1",
    "target": "variablesNode_789",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "variablesNode_789-RAGNode_711",
    "type": "defaultEdge",
    "source": "variablesNode_789",
    "target": "RAGNode_711",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "response-chatResponseNode_988",
    "type": "responseEdge",
    "source": "triggerNode_1",
    "target": "chatResponseNode_988",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger"
  }
];

export default { meta, inputs, references, nodes, edges };
