/*
 * # Article Summariser
 * This flow accepts an article URL, extracts the page content, and returns a concise summary as the canonical entrypoint for the wider URL-to-summary agent pipeline.
 *
 * ## Purpose
 * This flow is responsible for the core sub-task of turning a public web article into a short, readable summary. It solves the problem of quickly understanding long-form content without requiring a user or calling system to manually retrieve and read the full page. In practical terms, it receives a URL, scrapes the main article body, and hands that extracted text to a language model for summarisation.
 *
 * The outcome is a single summary string returned through the flow's API response. That output matters because it is the end product the wider agent system is designed to deliver: a compact representation of the article's key points that can be shown in a UI, passed into another automation, or stored for later use.
 *
 * Within the broader agent context, this is an entry-point flow in a simple retrieve-and-synthesize chain. It sits after invocation and before any hypothetical downstream enrichment, storage, or orchestration layers. In this kit, there are no separate planning or retrieval flows upstream; the flow itself performs retrieval through the scraper and synthesis through the LLM, then immediately returns the result.
 *
 * ## When To Use
 * - Use when a caller needs an on-demand summary of a public article available at a reachable `http` or `https` URL.
 * - Use when the desired input is a web page rather than pasted raw text, a file upload, or a document already stored in another system.
 * - Use when you want the system to extract the main readable content automatically before summarising it.
 * - Use when a backend service, UI action, or automation needs a synchronous API-style `url` to `summary` transformation.
 * - Use when no prior indexing, knowledge base ingestion, or multi-step research workflow is required and a direct single-article summary is sufficient.
 *
 * ## When Not To Use
 * - Do not use when the input is not a URL, such as raw article text, a PDF, an image, or an internal document identifier.
 * - Do not use when the target page is private, login-gated, blocked from the runtime, or otherwise inaccessible to the scraper.
 * - Do not use when you need summarisation across multiple articles in one request unless you first extend the flow to support batching explicitly.
 * - Do not use when the caller requires a full extraction, structured facts, citations, or classification output rather than a concise prose summary.
 * - Do not use when an upstream system has already extracted and normalized the content; in that case a text-to-summary flow would be a better fit than re-scraping.
 * - Do not use when credentials for the scraping provider or configured LLM provider are unavailable, because the flow depends on both stages completing successfully.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `url` | `string` | Yes | Public article URL supplied to the `API Request` trigger and passed into the `Scraper` node. |
 *
 * The flow source defines no explicit advanced trigger schema, so the input contract is inferred from downstream variable usage. The `Scraper` node reads `{{triggerNode_1.output.url}}`, which makes `url` the effective required field.
 *
 * Input should be a valid `http` or `https` URL pointing to an HTML page with extractable article content. The flow assumes the target page is reachable from the Lamatic runtime and contains enough readable main content for summarisation. No explicit max length, domain allowlist, or language restriction is defined in the flow, but extremely short pages, highly dynamic pages, and pages with little textual content may produce weak summaries.
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `summary` | `string` | Concise article summary generated by the `Generate Text` LLM node from the scraped page content. |
 *
 * The API response is a simple object containing a single prose field, `summary`. The value is mapped directly from `{{LLMNode_160.output.generatedResponse}}`, so the exact wording, length, and formatting depend on the configured prompts and model behavior.
 *
 * The output is intended to be human-readable rather than strongly structured. It may omit minor details from the source article, and completeness depends on how much relevant text the scraper was able to extract and how the LLM chooses to condense it.
 *
 * ## Dependencies
 * ### Upstream Flows
 * - None. This is a standalone entry-point flow invoked directly by an API request.
 * - The only prerequisite is that the caller provide a valid `url` value at invocation time.
 *
 * ### Downstream Flows
 * - None are defined in this kit. The flow returns its result directly to the caller.
 * - If extended in a larger system, downstream consumers would typically use the `summary` field for display, storage, search enrichment, or further reasoning.
 *
 * ### External Services
 * - Firecrawl-backed scraping via the `scraperNode` integration — used to fetch the target web page and extract readable main content — requires the scraping connector credentials configured in the Lamatic environment for the `Scraper` node.
 * - Configured LLM provider via `LLMNode` — used to generate the summary from scraped content using the referenced prompts and model configuration — requires the provider credentials associated with `@model-configs/article-summariser_generate-text.ts`.
 *
 * ### Environment Variables
 * - `FIRECRAWL_API_KEY` — enables page fetching and content extraction for the `Scraper` node.
 * - LLM provider credentials as required by `@model-configs/article-summariser_generate-text.ts` — enable summary generation in the `Generate Text` node. The exact variable names depend on the selected provider in that model config.
 *
 * ## Node Walkthrough
 * 1. `API Request` (`graphqlNode`)
 *    - This is the flow trigger and public entrypoint. It receives the incoming API payload and exposes request fields to downstream nodes.
 *    - In this flow, its practical role is to supply the `url` field that the scraper consumes.
 *
 * 2. `Scraper` (`scraperNode`)
 *    - This node fetches the page at `{{triggerNode_1.output.url}}` and extracts article content from it.
 *    - It is configured with `onlyMainContent` enabled, so the flow favors the primary readable article body over navigation, sidebars, and page chrome.
 *    - `mobile` is disabled, `waitFor` is set to `123`, and no tag inclusion or exclusion filters are configured. As a result, extraction behavior is broad but still oriented toward the main content region.
 *    - The output of this node is the retrieved page content used by the summarisation prompts referenced by the next node.
 *
 * 3. `Generate Text` (`LLMNode`)
 *    - This node takes the scraped article content and sends it to the configured language model along with a system prompt and a user prompt specific to article summarisation.
 *    - The prompts are referenced from `@prompts/article-summariser_generate-text_system.md` and `@prompts/article-summariser_generate-text_user.md`, and model behavior is controlled by `@model-configs/article-summariser_generate-text.ts`.
 *    - Its job in this specific flow is not general text generation, but focused condensation of the extracted article into a concise summary.
 *    - The node emits `generatedResponse`, which becomes the final `summary` returned by the flow.
 *
 * 4. `API Response` (`graphqlResponseNode`)
 *    - This node shapes the outward API response.
 *    - It maps a single field, `summary`, from `{{LLMNode_160.output.generatedResponse}}` and returns that object to the caller in realtime mode.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | Request fails before scraping starts | Missing or malformed `url` in the trigger payload | Ensure the API request includes a valid `url` string with an `http` or `https` scheme. |
 * | Scraper returns little or no usable content | The page is blocked, highly dynamic, non-article content, or inaccessible from the runtime | Test the URL manually, verify it is publicly reachable, and use pages with readable HTML article content. |
 * | Scraper authentication or connector error | Missing or invalid `FIRECRAWL_API_KEY` or scraper credential configuration | Configure the correct scraping credentials in the Lamatic environment and verify the integration is active. |
 * | Summary is empty or low quality | The scraped content was empty, extremely short, noisy, or poorly extracted | Check scraper output quality first, then adjust extraction settings or target a cleaner source page. |
 * | LLM node fails to run | Missing model provider credentials or invalid model configuration reference | Verify the credentials and provider settings required by `@model-configs/article-summariser_generate-text.ts`. |
 * | API response contains no `summary` | The `Generate Text` node did not produce `generatedResponse` due to upstream failure | Inspect scraper and LLM execution logs, fix the first failing node, and rerun the flow. |
 * | Caller expects this flow to consume prior pipeline outputs | No upstream flow exists because this flow is the entrypoint | Invoke this flow directly with `url`; do not wait for another flow unless you extend the kit. |
 *
 * ## Notes
 * - The flow metadata describes taking URLs in plural, but the implemented graph only maps a single field, `url`, from the trigger into the scraper.
 * - The response mode is configured as realtime, so the flow is intended for synchronous request-response usage rather than long-running background execution.
 * - Because `onlyMainContent` is enabled, summary quality is generally improved for standard article pages, but results can still vary on sites with unusual DOM structures.
 * - No explicit content moderation, language detection, deduplication, or retry logic is defined in the flow.
 * - The exact summary style, verbosity, and structure are governed by the external prompt files and model configuration rather than hardcoded node logic.
 */

// Flow: article-summariser

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Article Summariser",
  "description": "This workflow automates summarizing articles. It takes URLs, extracts content using Firecrawl, and generates concise summaries using an LLM, making it easier to quickly understand key points of long articles.",
  "tags": [
    "✨ Generative",
    "📞 Support"
  ],
  "testInput": null,
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": "https://studio.lamatic.ai/template/article-summariser",
  "author": {
    "name": "Naitik Kapadia",
    "email": "naitikk@lamatic.ai"
  }
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {};

// ── References ────────────────────────────────────────
// Cross-references to extracted resources in their own directories
// NOTE: Trigger widget settings are saved to triggers/widgets/ but NOT cross-referenced here
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "article_summariser_generate_text_user": "@prompts/article-summariser_generate-text_user.md",
    "article_summariser_generate_text_system": "@prompts/article-summariser_generate-text_system.md"
  },
  "modelConfigs": {
    "article_summariser_generate_text": "@model-configs/article-summariser_generate-text.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "type": "triggerNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlNode",
      "trigger": true,
      "values": {
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": ""
      }
    }
  },
  {
    "id": "scraperNode_252",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "scraperNode",
      "values": {
        "nodeName": "Scraper",
        "url": "{{triggerNode_1.output.url}}",
        "mobile": false,
        "waitFor": 123,
        "credentials": null,
        "excludeTags": [],
        "includeTags": [],
        "onlyMainContent": true,
        "skipTLsVerification": false
      }
    }
  },
  {
    "id": "LLMNode_160",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "LLMNode",
      "values": {
        "nodeName": "Generate Text",
        "tools": [],
        "prompts": [
          {
            "id": "201de7d9-b31f-4065-bbae-3363983ce3bf",
            "role": "user",
            "content": "@prompts/article-summariser_generate-text_user.md"
          },
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/article-summariser_generate-text_system.md"
          }
        ],
        "memories": "@model-configs/article-summariser_generate-text.ts",
        "messages": "@model-configs/article-summariser_generate-text.ts",
        "generativeModelName": "@model-configs/article-summariser_generate-text.ts"
      }
    }
  },
  {
    "id": "graphqlResponseNode_651",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlResponseNode",
      "values": {
        "nodeName": "API Response",
        "outputMapping": "{\n  \"summary\": \"{{LLMNode_160.output.generatedResponse}}\"\n}"
      }
    }
  }
];

export const edges = [
  {
    "id": "triggerNode_1-scraperNode_252",
    "source": "triggerNode_1",
    "target": "scraperNode_252",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "scraperNode_252-LLMNode_160",
    "source": "scraperNode_252",
    "target": "LLMNode_160",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "LLMNode_160-graphqlResponseNode_651",
    "source": "LLMNode_160",
    "target": "graphqlResponseNode_651",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "response-graphqlResponseNode_651",
    "source": "triggerNode_1",
    "target": "graphqlResponseNode_651",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger",
    "type": "responseEdge"
  }
];

export default { meta, inputs, references, nodes, edges };
