/*
 * # Teams Assistant
 * A Microsoft Teams bot flow that receives direct bot-chat messages, retrieves relevant knowledge from the configured vector index, and replies with a grounded answer as the Teams-facing assistant entry point in the wider internal knowledge system.
 *
 * ## Purpose
 * This flow is responsible for handling conversational question answering inside Microsoft Teams. It listens for inbound bot-chat messages, uses the message text as a retrieval query against an already-populated vector database, and generates a response through a retrieval-augmented generation step. Its job is not to ingest or index knowledge; instead, it turns previously indexed internal content into a usable Teams support experience for employees.
 *
 * The outcome of the flow is a contextual Teams reply based on the most relevant indexed content available in the selected vector store. That outcome matters because it gives end users a familiar collaboration interface for asking internal knowledge questions without leaving Teams. In practice, this makes the organization’s indexed documents, pages, and records accessible in a conversational format.
 *
 * Within the broader agent architecture, this flow sits on the retrieval-and-synthesis side of the pipeline. Upstream indexation flows are expected to have already collected enterprise content, chunked it, embedded it, and stored it in the vector database. This flow then performs the runtime retrieval step and the final answer synthesis step for the Microsoft Teams channel. It is therefore a channel-specific assistant flow parallel to sibling assistant flows such as web chat or Slack, rather than a general ingestion or orchestration flow.
 *
 * ## When To Use
 * - Use when employees need to ask questions from within Microsoft Teams and receive answers grounded in the organization’s indexed knowledge base.
 * - Use when a direct bot conversation in Teams should act as the entry point for an internal RAG assistant.
 * - Use when the relevant enterprise data has already been indexed into the configured vector database by one or more indexation flows.
 * - Use when the incoming interaction is a Teams bot-chat message and the desired behavior is to generate and send a reply automatically.
 * - Use when you want a Teams-native assistant experience instead of routing users to a separate web chatbot or another messaging platform.
 *
 * ## When Not To Use
 * - Do not use when the knowledge base has not yet been indexed; this flow assumes the vector store already contains usable embeddings and content.
 * - Do not use for ingestion, crawling, chunking, or vectorization tasks; those responsibilities belong to the kit’s indexation flows.
 * - Do not use when the user interaction originates from Slack or a web chat widget; the sibling assistant flow for that channel is the correct choice.
 * - Do not use when Teams credentials have not been configured, because both the trigger and the outbound reply depend on authenticated Teams access.
 * - Do not use when the incoming payload is not a Teams bot-chat event or does not contain message text suitable for retrieval.
 * - Do not use when you need group-channel routing logic beyond this flow’s configured conversation mode; this implementation is configured around Teams bot chat and replies using the triggering conversation context.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `credentials` | credential selector | Yes | Microsoft Teams credentials used by the trigger to authenticate and receive bot-chat events. This value is inherited from the outbound Teams node configuration. |
 *
 * Below the table, describe any notable input constraints or validation assumptions (e.g. max length, expected format, language).
 *
 * This flow is trigger-driven rather than invoked with a rich custom request schema. At runtime, the effective business input is the inbound Teams message text exposed as `triggerNode_1.output.text`, and that text is used directly as the retrieval query. The flow assumes the event comes from a valid Microsoft Teams bot conversation and includes a usable conversation context, message `id`, and `conversation.id` for sending the reply. No explicit length or language constraints are defined in the flow, but response quality depends on the selected retrieval and generation models and on the quality of the indexed content.
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `modelResponse` | string | The answer generated by the `RAG` node from retrieved knowledge and prompt instructions. |
 * | `message` | string or service response field | The message content sent back to Microsoft Teams, sourced from `RAGNode_233.output.modelResponse`. |
 * | `conversationId` | string | The Teams conversation identifier used to route the outgoing reply. |
 * | `channelMessageId` | string | The triggering message identifier used when replying in the originating message context. |
 *
 * Below the table, describe the output format in plain English — e.g. whether it is a list, a prose paragraph, a structured object — and any caveats about completeness or truncation.
 *
 * The user-visible output is a prose response posted back into Microsoft Teams. Internally, the key generated artifact is the `modelResponse` string from the retrieval step, which is then passed to the Teams send-message operation. The exact API response envelope is connector-defined and not fully declared in the flow source, so downstream consumers should treat the generated answer text as the canonical logical output. Completeness depends on retrieval quality, vector index coverage, prompt behavior, and any token or context limits enforced by the selected models.
 *
 * ## Dependencies
 * ### Upstream Flows
 * This is a channel entry-point flow for runtime question answering, so no upstream flow invokes it directly as part of the execution graph.
 *
 * However, it does depend on prior indexation flows having run successfully before it can produce useful answers. In the broader bundle, those ingestion flows must have already:
 * - Collected source content from enterprise systems such as web sources, cloud drives, SharePoint, OneDrive, S3, Postgres, or similar configured sources
 * - Normalized and chunked that content
 * - Embedded the chunks
 * - Stored them in the vector database selected by `RAGNode_233`
 *
 * At runtime, this flow consumes the following upstream data produced outside the flow itself:
 * - Indexed vector data in the selected `vectorDB`
 * - Teams bot event fields from the trigger, especially `triggerNode_1.output.text`, `triggerNode_1.output.id`, and `triggerNode_1.output.conversation.id`
 *
 * ### Downstream Flows
 * No downstream Lamatic flow is defined in this execution graph. This flow terminates by sending a message back to Microsoft Teams.
 *
 * Operationally, the response is consumed by the end user inside Teams. If an external orchestration layer monitors connector responses, it would most likely rely on the generated answer content and Teams delivery metadata, but no explicit downstream flow dependency is declared here.
 *
 * ### External Services
 * - Microsoft Teams — receives inbound bot-chat events and delivers the assistant’s reply — requires Teams `credentials`
 * - Vector database — stores and serves semantically searchable knowledge chunks for retrieval — requires the private `vectorDB` selection on `RAGNode_233`
 * - Embedding model — converts the inbound Teams query into vector space for similarity search — requires `embeddingModelName`
 * - Generative model — synthesizes the final answer from retrieved context and prompts — requires `generativeModelName`
 * - Prompt resources — provide the system and user instructions that shape RAG behavior — referenced by `teams_assistant_rag_system` and `teams_assistant_rag_user`
 * - Model configuration resource — supplies retrieval/generation settings such as `limit`, `memories`, `messages`, and `certainty` — referenced by `teams_assistant_rag`
 *
 * ### Environment Variables
 * - None explicitly declared in the flow source — this flow uses private configured inputs rather than named environment variables — used by `triggerNode_1`, `RAGNode_233`, and `teamsNode_784` through Lamatic-managed configuration
 *
 * ## Node Walkthrough
 * 1. `Teams` (`triggerNode`) starts the flow when a Microsoft Teams bot-chat event is received. It is configured with `conversationType` set to `botChat`, so the flow is specifically listening for direct bot conversation traffic. From the incoming event, it exposes the user’s message text as `triggerNode_1.output.text`, along with reply-routing metadata such as the message `id` and `conversation.id`.
 *
 * 2. `RAG` (`dynamicNode`) takes the inbound Teams message text and uses it as the retrieval query through `queryField` mapped from `{{triggerNode_1.output.text}}`. It searches the configured `vectorDB` using the selected `embeddingModelName`, applies retrieval settings from `@model-configs/teams-assistant_rag.ts`, and then generates an answer using the selected `generativeModelName`. The answer is shaped by the referenced system and user prompts and returned as `RAGNode_233.output.modelResponse`.
 *
 * 3. `Teams` (`dynamicNode`) sends the generated answer back to Microsoft Teams. Its `message` field is mapped from `{{RAGNode_233.output.modelResponse}}`, and it uses the trigger-derived `conversation.id` and message `id` to route the reply into the originating conversation context. The node is configured for Teams send-message behavior and includes `includePoweredBy` enabled.
 *
 * 4. `addNode` (`addNode`) is a canvas placeholder rather than an operational processing step. It does not contribute business logic or transform flow data.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | The flow never triggers on Teams messages | Teams `credentials` are missing, invalid, or the bot is not correctly connected to Microsoft Teams | Reconfigure the Teams credential on `teamsNode_784`, verify the trigger inherited it correctly on `triggerNode_1`, and confirm the bot is installed and permitted to receive direct bot-chat events |
 * | The bot triggers but returns no useful answer | The vector database is empty, the wrong `vectorDB` was selected, or upstream indexation flows have not populated the knowledge base | Run the appropriate indexation flow first, verify content exists in the selected vector store, and confirm `RAGNode_233` points to the intended database |
 * | The assistant responds with irrelevant content | The selected embedding or generative model is poorly matched to the data, retrieval settings are misconfigured, or indexed content quality is weak | Review `embeddingModelName`, `generativeModelName`, and the referenced model config; re-index cleaner content if necessary |
 * | The flow fails at the RAG step | Required private inputs for `vectorDB`, `embeddingModelName`, or `generativeModelName` were not configured | Populate all required private inputs on `RAGNode_233` before deployment |
 * | The bot cannot send the reply back to Teams | Outbound Teams credentials are invalid, the conversation context is missing, or the conversation/message identifiers from the trigger are malformed | Validate Teams authentication, inspect the trigger payload for `conversation.id` and `id`, and confirm the bot has permission to post into the conversation |
 * | A user asks a question but receives an incomplete or truncated answer | Model token limits, retrieval limits, or prompt constraints reduced the amount of context or output length | Adjust the referenced model configuration, review retrieval `limit` behavior, and test with a model that supports the required context window |
 * | The flow is deployed but answers are stale or missing recent documents | Upstream indexation flows have not run recently or new source content was never embedded into the vector store | Re-run the relevant ingestion/indexation flow and confirm the new content was chunked, embedded, and stored in the same database this assistant queries |
 * | Non-Teams invocations fail or produce malformed inputs | This flow expects a Teams bot-chat trigger and is not designed for arbitrary API-style payloads | Route non-Teams traffic to the appropriate assistant flow, such as the web or Slack variant, instead of reusing this trigger |
 *
 * ## Notes
 * - This flow is tightly channel-bound: it is the Microsoft Teams assistant surface for the internal knowledge system, not a generic reusable RAG endpoint.
 * - The trigger is configured for `botChat`, which indicates a direct bot conversation pattern rather than a broad multi-channel or generalized webhook intake.
 * - The reply node uses both `conversationId` and `channelMessageId` from the trigger context, so successful response delivery depends on preserving the event metadata emitted by Teams.
 * - The RAG node’s detailed retrieval behavior is partly externalized into `@model-configs/teams-assistant_rag.ts`; operators should review that resource when tuning retrieval depth, memory behavior, or answer style.
 * - Prompt behavior is also externalized. Changes to `@prompts/teams-assistant_rag_system.md` and `@prompts/teams-assistant_rag_user.md` can materially change grounding, tone, and response structure without altering the flow graph.
 * - Because the flow uses private configuration inputs for credentials and model selection, portability between environments depends on correctly re-binding those private values after import or deployment.
 */

// Flow: teams-assistant

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Teams Assistant",
  "description": "Contextual Microsoft teams bot with knowledge from Content",
  "tags": [],
  "testInput": null,
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": "",
  "author": {
    "name": "Naitik Kapadia",
    "email": "naitikk@lamatic.ai"
  }
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {
  "RAGNode_233": [
    {
      "isDB": true,
      "name": "vectorDB",
      "type": "select",
      "label": "Database",
      "required": true,
      "isPrivate": true,
      "description": "Select the vector database to be queried.",
      "defaultValue": ""
    },
    {
      "mode": "embedding",
      "name": "embeddingModelName",
      "type": "model",
      "label": "Embedding Model Name",
      "required": true,
      "isPrivate": true,
      "modelType": "embedder/text",
      "description": "This field allows the user to select the embedding model used to embed the query into vector space. It loads available embedding models through the listModels method.",
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      },
      "defaultValue": ""
    },
    {
      "mode": "chat",
      "name": "generativeModelName",
      "type": "model",
      "label": "Generative Model Name",
      "required": true,
      "isPrivate": true,
      "modelType": "generator/text",
      "description": "Select the model to generate responses from the query results.",
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      },
      "defaultValue": ""
    }
  ],
  "teamsNode_784": [
    {
      "name": "credentials",
      "type": "select",
      "label": "Credentials",
      "required": true,
      "isPrivate": true,
      "description": "Select the credentials for Teams authentication.",
      "defaultValue": "",
      "isCredential": true
    }
  ],
  "triggerNode_1": [
    {
      "name": "credentials",
      "type": "select",
      "label": "Credentials",
      "required": true,
      "isPrivate": true,
      "description": "Select the credentials for Teams authentication.",
      "defaultValue": "",
      "fillFromStep": {
        "name": "credentials",
        "step": 0,
        "nodeId": "teamsNode_784"
      },
      "isCredential": true
    }
  ]
};

// ── References ────────────────────────────────────────
// Cross-references to extracted resources in their own directories
// NOTE: Trigger widget settings are saved to triggers/widgets/ but NOT cross-referenced here
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "teams_assistant_rag_system": "@prompts/teams-assistant_rag_system.md",
    "teams_assistant_rag_user": "@prompts/teams-assistant_rag_user.md"
  },
  "modelConfigs": {
    "teams_assistant_rag": "@model-configs/teams-assistant_rag.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "type": "triggerNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "teamsNode",
      "modes": {
        "chatId": "list",
        "teamId": "list",
        "channelId": "list"
      },
      "trigger": true,
      "values": {
        "nodeName": "Teams",
        "conversationType": "botChat"
      }
    }
  },
  {
    "id": "RAGNode_233",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "RAGNode",
      "modes": {},
      "values": {
        "nodeName": "RAG",
        "limit": "@model-configs/teams-assistant_rag.ts",
        "filters": "",
        "prompts": [
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/teams-assistant_rag_system.md"
          },
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7d",
            "role": "user",
            "content": "@prompts/teams-assistant_rag_user.md"
          }
        ],
        "memories": "@model-configs/teams-assistant_rag.ts",
        "messages": "@model-configs/teams-assistant_rag.ts",
        "certainty": "@model-configs/teams-assistant_rag.ts",
        "queryField": "{{triggerNode_1.output.text}}"
      }
    }
  },
  {
    "id": "teamsNode_784",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "teamsNode",
      "modes": {
        "chatId": "list",
        "teamId": "list",
        "channelId": "list"
      },
      "values": {
        "nodeName": "Teams",
        "message": "{{RAGNode_233.output.modelResponse}}",
        "botOperation": "sendMessage",
        "chatOperation": "sendMessage",
        "channelMessageId": "{{triggerNode_1.output.id}}",
        "channelOperation": "replyToMessage",
        "conversationId": "{{triggerNode_1.output.conversation.id}}",
        "conversationType": "bot",
        "includePoweredBy": true
      }
    }
  },
  {
    "id": "plus-node-addNode_557807",
    "type": "addNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "addNode",
      "values": {
        "nodeName": ""
      }
    }
  }
];

export const edges = [
  {
    "id": "triggerNode_1-RAGNode_233",
    "source": "triggerNode_1",
    "target": "RAGNode_233",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "RAGNode_233-teamsNode_784",
    "source": "RAGNode_233",
    "target": "teamsNode_784",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "teamsNode_784-plus-node-addNode_557807",
    "source": "teamsNode_784",
    "target": "plus-node-addNode_557807",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  }
];

export default { meta, inputs, references, nodes, edges };
