/*
 * # Release Notes Generator
 * This flow accepts a block of raw git commit messages and/or pull request titles and returns
 * polished, categorized release notes in Markdown as the single entrypoint of the kit.
 *
 * ## Purpose
 * This flow turns raw version-control history into human-readable release notes. It solves the
 * common developer chore of manually reading through commits and PR titles to summarise "what
 * changed" for a release. It receives a plain-text `changes` field (one commit/PR per line),
 * sends it to a language model with a release-manager system prompt, and returns grouped,
 * rewritten notes (Features / Fixes / Breaking Changes / Maintenance).
 *
 * ## When To Use
 * - Use when you have a list of commit messages or PR titles and want ready-to-publish notes.
 * - Use when a CI/CD step or release script needs a synchronous `changes` -> `releaseNotes` call.
 * - Use when you want Conventional Commit prefixes (feat:, fix:, chore:) auto-categorized.
 *
 * ## When Not To Use
 * - Do not use when you need the raw diff analyzed line-by-line; this consumes commit/PR text only.
 * - Do not use when you require exact commit hashes or author attribution preserved verbatim.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `changes` | `string` | Yes | Newline-separated commit messages and/or PR titles. |
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `releaseNotes` | `string` | Categorized release notes in Markdown generated by the LLM node. |
 *
 * ## Node Walkthrough
 * 1. `API Request` (`graphqlNode`) — trigger; exposes the `changes` field.
 * 2. `Generate Text` (`LLMNode`) — sends `changes` to the model with the system/user prompts.
 * 3. `API Response` (`graphqlResponseNode`) — maps `releaseNotes` from the LLM output.
 */

// Flow: release-notes-generator

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Release Notes Generator",
  "description": "This workflow turns raw git commit messages and pull request titles into clean, categorized, human-readable release notes using an LLM.",
  "tags": [
    "✨ Generative",
    "🛠️ Developer Tools"
  ],
  "testInput": null,
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": "https://studio.lamatic.ai/template/release-notes-generator",
  "author": {
    "name": "Shaik Shivaji",
    "email": "shaikshivaji123@gmail.com"
  }
};

// ── Inputs ────────────────────────────────────────────
// The `changes` field is the required, untrusted payload for this flow.
// A max length guard keeps oversized requests from reaching the LLM node.
export const inputs = {
  "changes": {
    "type": "string",
    "title": "changes",
    "description": "Newline-separated git commit messages and/or pull request titles.",
    "required": true,
    "maxLength": 20000
  }
};

// ── References ────────────────────────────────────────
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "release_notes_generator_generate_text_user": "@prompts/release-notes-generator_generate-text_user.md",
    "release_notes_generator_generate_text_system": "@prompts/release-notes-generator_generate-text_system.md"
  },
  "modelConfigs": {
    "release_notes_generator_generate_text": "@model-configs/release-notes-generator_generate-text.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "type": "triggerNode",
    "position": { "x": 0, "y": 0 },
    "data": {
      "nodeId": "graphqlNode",
      "trigger": true,
      "values": {
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": "{\"type\":\"object\",\"properties\":{\"changes\":{\"type\":\"string\",\"title\":\"changes\",\"description\":\"Newline-separated git commit messages and/or pull request titles.\",\"maxLength\":20000}},\"required\":[\"changes\"]}"
      }
    }
  },
  {
    "id": "LLMNode_160",
    "type": "dynamicNode",
    "position": { "x": 0, "y": 0 },
    "data": {
      "nodeId": "LLMNode",
      "values": {
        "nodeName": "Generate Text",
        "tools": [],
        "prompts": [
          {
            "id": "b1a2c3d4-0001-4000-8000-000000000001",
            "role": "user",
            "content": "@prompts/release-notes-generator_generate-text_user.md"
          },
          {
            "id": "b1a2c3d4-0002-4000-8000-000000000002",
            "role": "system",
            "content": "@prompts/release-notes-generator_generate-text_system.md"
          }
        ],
        "memories": "@model-configs/release-notes-generator_generate-text.ts",
        "messages": "@model-configs/release-notes-generator_generate-text.ts",
        "generativeModelName": "@model-configs/release-notes-generator_generate-text.ts"
      }
    }
  },
  {
    "id": "graphqlResponseNode_651",
    "type": "dynamicNode",
    "position": { "x": 0, "y": 0 },
    "data": {
      "nodeId": "graphqlResponseNode",
      "values": {
        "nodeName": "API Response",
        "outputMapping": "{\n  \"releaseNotes\": \"{{LLMNode_160.output.generatedResponse}}\"\n}"
      }
    }
  }
];

export const edges = [
  {
    "id": "triggerNode_1-LLMNode_160",
    "source": "triggerNode_1",
    "target": "LLMNode_160",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "LLMNode_160-graphqlResponseNode_651",
    "source": "LLMNode_160",
    "target": "graphqlResponseNode_651",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "response-graphqlResponseNode_651",
    "source": "triggerNode_1",
    "target": "graphqlResponseNode_651",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger",
    "type": "responseEdge"
  }
];

export default { meta, inputs, references, nodes, edges };
