export const config = {
  api: {
    endpoint: process.env.NEXT_PUBLIC_LAMATIC_ENDPOINT ?? "",
    projectId: process.env.NEXT_PUBLIC_LAMATIC_PROJECT_ID ?? "",
    apiKey: process.env.LAMATIC_API_KEY ?? "",
  },
  flows: {
    pricing: {
      name: "Forge Pricing",
      workflowId: process.env.NEXT_PUBLIC_FLOW_PRICING ?? "",
      inputSchema: {
        work_type: "string",
        field: "string",
        experience_level: "string",
        years_of_experience: "string",
        deliverables: "string",
        payment_structure: "string",
        currency: "string",
        freelancer_country: "string",
        client_country: "string",
      },
    },
    tradeoff: {
      name: "Forge Tradeoff",
      workflowId: process.env.NEXT_PUBLIC_FLOW_TRADEOFF ?? "",
      inputSchema: {
        freelancer_name: "string",
        freelancer_country: "string",
        freelancer_payment_method: "string",
        freelancer_primary_concern: "string",
        client_name: "string",
        client_country: "string",
        client_type: "string",
        project_title: "string",
        project_description: "string",
        deliverables: "string",
        timeline_start: "string",
        timeline_end: "string",
        payment_amount: "string",
        payment_currency: "string",
        payment_structure: "string",
        work_type: "string",
      },
    },
    contract: {
      name: "Forge Contract",
      workflowId: process.env.NEXT_PUBLIC_FLOW_CONTRACT ?? "",
      inputSchema: {
        freelancer_name: "string",
        freelancer_country: "string",
        freelancer_payment_method: "string",
        freelancer_primary_concern: "string",
        client_name: "string",
        client_country: "string",
        client_type: "string",
        project_title: "string",
        project_description: "string",
        deliverables: "string",
        timeline_start: "string",
        timeline_end: "string",
        payment_amount: "string",
        payment_currency: "string",
        payment_structure: "string",
        work_type: "string",
        chosen_governing_law: "string",
      },
    },
    invoice: {
      name: "Forge Invoice",
      workflowId: process.env.NEXT_PUBLIC_FLOW_INVOICE ?? "",
      inputSchema: {
        freelancer_name: "string",
        freelancer_address: "string",
        freelancer_country: "string",
        freelancer_email: "string",
        freelancer_payment_details: "string",
        client_name: "string",
        client_address: "string",
        client_country: "string",
        client_email: "string",
        invoice_date: "string",
        due_date: "string",
        project_title: "string",
        line_items: "string",
        currency: "string",
        total_amount: "string",
        payment_instructions: "string",
        notes: "string",
      },
    },
  },
};
