"use client";

import { useState } from "react";
import type { Diagnosis, ExportFormat, WorkspaceMetadata } from "@/lib/types";

interface WorkspaceExportModalProps {
  diagnosis: Diagnosis;
  metadata?: WorkspaceMetadata | null;
  onClose: () => void;
}

export function WorkspaceExportModal({ diagnosis, metadata, onClose }: WorkspaceExportModalProps) {
  const [format, setFormat] = useState<ExportFormat>("markdown");
  const [copied, setCopied] = useState(false);

  const generateMarkdown = () => {
    return `# CI/CD Diagnosis Report
**Generated by AgentKit AI** — ${new Date().toLocaleString()}

## Execution Context
- **Repository**: ${metadata?.repoOwner && metadata?.repoName ? `${metadata.repoOwner}/${metadata.repoName}` : "Manual Upload"}
- **Branch**: ${metadata?.branch || "main"}
- **Commit SHA**: ${metadata?.commitSha || "beb0902"}
- **Run Number**: #${metadata?.runNumber || 142}

---

## AI Diagnosis
- **Category**: ${diagnosis.classification.category} (${diagnosis.classification.sub_category || "General"})
- **Confidence**: ${Math.round(diagnosis.classification.confidence_score * 100)}%
- **Risk Level**: ${diagnosis.risk.level}

### Root Cause
> ${diagnosis.analysis.root_cause_summary}

${diagnosis.analysis.detailed_explanation}

### Evidence Cited
${diagnosis.analysis.evidence_cited.map((e) => `- \`${e}\``).join("\n")}

---

## Suggested Verified Fixes
${diagnosis.resolution.fixes.map((f) => `### ${f.description}\n\`\`\`${f.language}\n${f.code}\n\`\`\``).join("\n\n")}

### Security Review
${diagnosis.resolution.security_warnings || diagnosis.risk.warning || "No security risks detected."}
`;
  };

  const generateJson = () => {
    return JSON.stringify({ metadata, diagnosis }, null, 2);
  };

  const generateText = () => {
    return `CI/CD DIAGNOSIS REPORT
Root Cause: ${diagnosis.analysis.root_cause_summary}
Confidence: ${Math.round(diagnosis.classification.confidence_score * 100)}%
Risk: ${diagnosis.risk.level}

Fix:
${diagnosis.resolution.fixes.map((f) => `${f.description}:\n${f.code}`).join("\n\n")}
`;
  };

  const getExportContent = () => {
    if (format === "json") return generateJson();
    if (format === "text") return generateText();
    return generateMarkdown();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getExportContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = getExportContent();
    const ext = format === "json" ? "json" : format === "text" ? "txt" : "md";
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `diagnosis-report-${Date.now()}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 animate-fade-in">
      <div className="glass-panel w-full max-w-xl rounded-[24px] p-6 space-y-5 border border-white/20 shadow-2xl">
        <div className="flex items-center justify-between border-b border-white/10 pb-4">
          <h3 className="text-base font-semibold text-white">Export & Share Diagnosis Report</h3>
          <button
            onClick={onClose}
            className="text-lg text-[var(--muted)] hover:text-white transition-all"
          >
            ×
          </button>
        </div>

        {/* Format Selector Tabs */}
        <div className="flex gap-2">
          {[
            { id: "markdown", label: "Markdown (.md)" },
            { id: "json", label: "JSON (.json)" },
            { id: "text", label: "Plain Text (.txt)" },
          ].map((item) => (
            <button
              key={item.id}
              onClick={() => setFormat(item.id as ExportFormat)}
              className={`rounded-[12px] px-3.5 py-1.5 text-xs font-medium transition-all ${
                format === item.id
                  ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/40"
                  : "bg-white/5 text-[var(--muted)] hover:text-white"
              }`}
            >
              {item.label}
            </button>
          ))}
        </div>

        {/* Content Preview */}
        <pre className="max-h-64 overflow-y-auto rounded-[16px] bg-black/60 p-4 font-mono text-xs text-cyan-200 border border-white/5 whitespace-pre-wrap">
          {getExportContent()}
        </pre>

        {/* Action Buttons */}
        <div className="flex justify-end gap-3 pt-2">
          <button
            onClick={handleCopy}
            className="rounded-[14px] border border-white/10 bg-white/10 px-4 py-2 text-xs font-semibold text-white hover:bg-white/20 transition-all"
          >
            {copied ? "✓ Copied to Clipboard" : "Copy to Clipboard"}
          </button>

          <button
            onClick={handleDownload}
            className="apple-button rounded-[14px] px-5 py-2 text-xs font-semibold shadow-md"
          >
            Download File ↓
          </button>
        </div>
      </div>
    </div>
  );
}
