/*
 * # Intake Agent
 * STUB — not yet built in Lamatic Studio. This file will be replaced by the real export
 * (meta/inputs/references/nodes/edges) once the flow is built there. See README.md's Setup
 * section for the build order.
 *
 * ## Purpose
 * Parses a raw customer message into a structured booking request and checks it's complete
 * enough to hand off to the Scheduling Agent. First agent in the pipeline.
 *
 * ## Trigger
 * API request (graphqlNode). MVP input: a raw chat message. Stretch: a Twilio call transcript.
 *
 * ## Planned Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `message` | `string` | Yes | Raw customer message text. |
 * | `session_id` | `string` | Yes | Session identifier, generated by the Next.js app. |
 *
 * ## Planned Node Walkthrough
 * 1. `API Request` (trigger, graphqlNode) — receives `message` and `session_id`.
 * 2. `Extraction` (LLMNode) — parses `message` into service_type, preferred_date,
 *    preferred_window, name, phone, notes. System prompt:
 *    `@prompts/intake-agent_extract-request_system.md`.
 * 3. `Validation` (branchNode/conditionNode) — checks required fields (service_type,
 *    preferred_date OR preferred_window, name, phone) are present.
 *    - Missing → route to a clarifying-question response.
 *    - Complete → route to the success response.
 * 4. `API Response` (responseNode) — returns either a clarifying question or the structured
 *    request object, matching the `request` shape in the shared session contract (see
 *    top-level README.md).
 *
 * ## Planned Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `needs_clarification` | `boolean` | True if required fields were missing. |
 * | `clarifying_question` | `string \| null` | Present when `needs_clarification` is true. |
 * | `request` | `object \| null` | Structured booking request, present when complete. |
 *
 * ## Dependencies
 * - LLM provider for the Extraction node.
 * - No external services.
 */

export {};
