/*
 * # Intake Agent
 * BUILT AND TESTED in Lamatic Studio (Zaid's Organization / ZaidsProject406, model
 * claude-haiku-4-5). Not yet exported into this file — do that via Studio's export menu once
 * the flow's Flow ID is copied into .env as INTAKE_AGENT. Until then this remains a doc-only
 * stub describing the real, already-built node graph.
 *
 * ## Purpose
 * Parses a raw customer message into a structured booking request and checks it's complete
 * enough to hand off to the Scheduling Agent. First agent in the pipeline.
 *
 * ## Trigger
 * API request (graphqlNode). Schema: `{ message: string, session_id: string }`.
 *
 * ## Node Walkthrough (as built)
 * 1. `API Request` (trigger) — receives `message` and `session_id`.
 * 2. `Extraction` (Generate JSON / InstructorLLMNode, claude-haiku-4-5) — parses `message` into
 *    service_type, preferred_date, preferred_window, name, phone, notes. Every field is typed
 *    `string`; only `service_type` is `required`. System prompt:
 *    `@prompts/intake-agent_extract-request_system.md`. The prompt explicitly requires an empty
 *    string `""` (never the word "null") for anything not stated — the schema has no true
 *    nullable type, so asking the model for JSON `null` produced sentinel text like "<UNKNOWN>"
 *    instead. See docs/decision-log.md.
 * 3. `Condition` — checks `{{Extraction.output.service_type}} != ""`.
 *    - `Else` (empty) → `Prepare Clarification` (codeNode): sets `needs_clarification: true`
 *      and a clarifying question (from `@prompts/intake-agent_extract-request_system.md`-style
 *      reasoning, hardcoded per-field for now).
 *    - `Condition 1` (present) → `Prepare Success Response` (codeNode): sets
 *      `needs_clarification: false` and `request` to the full Extraction output object.
 * 4. `API Response` — output mapping pulls `needs_clarification`/`clarifying_question` from
 *    `Prepare Clarification`'s output and `request` (type `obj`... actually mapped as `str`
 *    referencing the object directly, which Lamatic serializes correctly) from `Prepare Success
 *    Response`'s output. One source node per field, not per branch — see decision log for why
 *    this resolves correctly regardless of which branch actually ran.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `message` | `string` | Yes | Raw customer message text. |
 * | `session_id` | `string` | Yes | Session identifier, generated by the Next.js app. |
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `needs_clarification` | `boolean` | True if `service_type` was missing. |
 * | `clarifying_question` | `string` | Present (non-empty) when `needs_clarification` is true. |
 * | `request` | `object` | Structured booking request; populated when complete. |
 *
 * ## Dependencies
 * - LLM provider for the Extraction node (Anthropic credential, claude-haiku-4-5).
 * - No external services.
 *
 * ## Known limitation
 * `preferred_date` is not normalized to an absolute date — the model doesn't know today's date,
 * so relative phrases like "tomorrow" are returned as-is. Acceptable for MVP.
 */

export {};
