/*
 * # Negotiation Coach
 * This flow accepts a plain-text description of a negotiation scenario and returns a complete, structured negotiation playbook generated by an LLM acting as a world-class negotiation strategist.
 *
 * ## Purpose
 * This flow solves the problem of entering high-stakes negotiations unprepared. Whether it's a salary discussion, a vendor contract, a freelance rate, a rent negotiation, or a business deal — most people go in without a clear strategy, don't know their walk-away point, and get caught off-guard by predictable counter-arguments.
 *
 * The flow accepts a `scenario` string from the caller, passes it to a language model primed with deep negotiation expertise, and returns a fully structured `strategy` document containing: a psychological framing approach, a word-for-word opening script, a table of anticipated objections with prepared responses, a BATNA (Best Alternative to a Negotiated Agreement) analysis, and a list of scenario-specific traps to avoid.
 *
 * Within the broader agent context, this is a standalone, synchronous entry-point flow. It requires no prior indexing, knowledge base, memory, or multi-step orchestration. A caller provides a scenario description and immediately receives an actionable playbook.
 *
 * ## When To Use
 * - Use when a person needs to prepare for an upcoming negotiation and wants structured, scenario-specific strategic advice.
 * - Use when the input is a free-text description of a deal, discussion, or negotiation context (salary, vendor, freelance, rent, purchase, partnership, etc.).
 * - Use when a backend service, UI, or automation needs a synchronous `scenario` → `strategy` transformation.
 * - Use when no prior document ingestion, memory, or multi-turn conversation is required.
 *
 * ## When Not To Use
 * - Do not use when the caller requires legal advice, binding contract review, or financial planning — this flow produces strategic coaching, not professional legal or financial counsel.
 * - Do not use when the scenario description is extremely vague (e.g., "I want to negotiate something") without any context — output quality degrades without specifics.
 * - Do not use when a multi-turn, interactive coaching conversation is needed — this flow is single-shot, not a chat loop.
 * - Do not use when the negotiation involves highly technical legal clauses that require a licensed attorney's interpretation.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `scenario` | `string` | Yes | Plain-text description of the negotiation scenario. Should include context: what is being negotiated, who the parties are, current offer or situation, and the desired outcome. |
 *
 * Input should be a clear, specific description of the situation. The more context provided (current offer, desired outcome, relationship with the other party, timeline), the higher the quality of the generated strategy.
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `strategy` | `string` | A fully structured negotiation playbook in markdown format, containing: Framing Strategy, Opening Script, Counter-Arguments table, BATNA analysis, and Traps to Avoid. |
 *
 * ## Dependencies
 * ### Upstream Flows
 * - None. This is a standalone entry-point flow invoked directly by an API request.
 *
 * ### Downstream Flows
 * - None. The flow returns its result directly to the caller.
 *
 * ### External Services
 * - Configured LLM provider via `LLMNode` — requires provider credentials associated with `@model-configs/negotiation-coach_generate-text.ts`.
 *
 * ### Environment Variables
 * - LLM provider credentials as required by `@model-configs/negotiation-coach_generate-text.ts` (e.g., `OPENAI_API_KEY` or `ANTHROPIC_API_KEY` depending on the configured model).
 *
 * ## Node Walkthrough
 * 1. `API Request` (`graphqlNode`)
 *    - The flow trigger and public entrypoint. Receives the incoming API payload and exposes the `scenario` field to downstream nodes.
 *
 * 2. `Generate Text` (`LLMNode`)
 *    - Takes the negotiation scenario from `{{triggerNode_1.output.scenario}}` and sends it to the configured language model.
 *    - System prompt (`@prompts/negotiation-coach_generate-text_system.md`) primes the model as a world-class negotiation strategist and enforces a strict structured output format.
 *    - User prompt (`@prompts/negotiation-coach_generate-text_user.md`) injects the caller's scenario description.
 *    - Emits `generatedResponse` which becomes the final `strategy` returned by the flow.
 *
 * 3. `API Response` (`graphqlResponseNode`)
 *    - Maps `strategy` from `{{LLMNode_201.output.generatedResponse}}` and returns it to the caller in realtime mode.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | Request fails immediately | Missing or empty `scenario` in the trigger payload | Ensure the API request includes a non-empty `scenario` string. |
 * | Strategy output is generic or low quality | The scenario description was too vague | Ask the caller to include more context: current offer, desired outcome, timeline, relationship with other party. |
 * | LLM node fails to run | Missing model provider credentials or invalid model configuration | Verify the credentials required by `@model-configs/negotiation-coach_generate-text.ts`. |
 * | API response contains no `strategy` field | The `Generate Text` node did not produce `generatedResponse` due to upstream failure | Inspect LLM execution logs, fix the failing node, and rerun the flow. |
 *
 * ## Notes
 * - The response mode is configured as realtime, so this flow is intended for synchronous request-response usage.
 * - Output quality scales with scenario specificity. Very short inputs produce usable but less tailored advice.
 * - No memory, retrieval, or multi-step reasoning is used — this is a single-pass LLM inference flow.
 * - The disclaimer in the system prompt reminds users this is coaching, not legal advice.
 */

// Flow: negotiation-coach

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Negotiation Coach",
  "description": "AI-powered negotiation strategy generator. Describe your negotiation scenario (salary, vendor contract, freelance rate, rent, or any deal) and receive a complete, structured playbook: framing strategy, opening script, anticipated counter-arguments with responses, BATNA analysis, and traps to avoid.",
  "tags": [
    "💼 Negotiation",
    "🚀 Productivity",
    "🎯 Career",
    "✨ Startup"
  ],
  "testInput": {
    "scenario": "I am a software engineer with 4 years of experience. I have a competing offer of $120,000 from another company. My current employer has offered me a raise to $105,000 during my annual review. I want to negotiate up to at least $115,000 and also ask for an extra 5 days of PTO. My manager is generally reasonable but very budget-conscious."
  },
  "githubUrl": "https://github.com/Lamatic/AgentKit/tree/main/kits/negotiation-coach",
  "documentationUrl": "",
  "deployUrl": "",
  "author": {
    "name": "Anuj Rajput",
    "email": "anujrajput@example.com"
  }
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {};

// ── References ────────────────────────────────────────
// Cross-references to extracted resources in their own directories
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "negotiation_coach_generate_text_system": "@prompts/negotiation-coach_generate-text_system.md",
    "negotiation_coach_generate_text_user": "@prompts/negotiation-coach_generate-text_user.md"
  },
  "modelConfigs": {
    "negotiation_coach_generate_text": "@model-configs/negotiation-coach_generate-text.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "type": "triggerNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlNode",
      "trigger": true,
      "values": {
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": ""
      }
    }
  },
  {
    "id": "LLMNode_201",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 200
    },
    "data": {
      "nodeId": "LLMNode",
      "values": {
        "nodeName": "Generate Strategy",
        "tools": [],
        "prompts": [
          {
            "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "role": "system",
            "content": "@prompts/negotiation-coach_generate-text_system.md"
          },
          {
            "id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
            "role": "user",
            "content": "@prompts/negotiation-coach_generate-text_user.md"
          }
        ],
        "memories": "@model-configs/negotiation-coach_generate-text.ts",
        "messages": "@model-configs/negotiation-coach_generate-text.ts",
        "generativeModelName": "@model-configs/negotiation-coach_generate-text.ts"
      }
    }
  },
  {
    "id": "graphqlResponseNode_301",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 400
    },
    "data": {
      "nodeId": "graphqlResponseNode",
      "values": {
        "nodeName": "API Response",
        "outputMapping": "{\n  \"strategy\": \"{{LLMNode_201.output.generatedResponse}}\"\n}"
      }
    }
  }
];

export const edges = [
  {
    "id": "triggerNode_1-LLMNode_201",
    "source": "triggerNode_1",
    "target": "LLMNode_201",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "LLMNode_201-graphqlResponseNode_301",
    "source": "LLMNode_201",
    "target": "graphqlResponseNode_301",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "response-graphqlResponseNode_301",
    "source": "triggerNode_1",
    "target": "graphqlResponseNode_301",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger",
    "type": "responseEdge"
  }
];

export default { meta, inputs, references, nodes, edges };
