import type { AuditReport, Finding } from "./types";
import { SEVERITY_RANK, SEVERITY_LABEL, normalizeSeverity } from "./severity";

const SEV_HEX: Record<string, string> = {
  critical: "#d92d20",
  high: "#e04f16",
  medium: "#f79009",
  low: "#2e90fa",
  info: "#667085",
};

function sortFindings(findings: Finding[]): Finding[] {
  return [...findings].sort(
    (a, b) => SEVERITY_RANK[normalizeSeverity(a.severity)] - SEVERITY_RANK[normalizeSeverity(b.severity)]
  );
}

function esc(s: string): string {
  return (s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function toJSON(report: AuditReport): string {
  return JSON.stringify(report, null, 2);
}

export function toMarkdown(report: AuditReport): string {
  const out: string[] = [];
  out.push("# DockerGuard audit report", "");
  out.push(`- **Score:** ${Number(report.score) || 0}/100`);
  out.push(`- **Grade:** ${report.grade}`);
  out.push(`- **Detected type:** ${report.input_type}`);
  out.push(`- **Findings:** ${report.findings?.length ?? 0}`, "");
  if (report.summary) out.push(`> ${report.summary}`, "");

  out.push("## Findings", "");
  const findings = sortFindings(report.findings ?? []);
  if (findings.length === 0) out.push("No issues found.", "");
  for (const f of findings) {
    const sev = normalizeSeverity(f.severity);
    out.push(`### ${SEVERITY_LABEL[sev]} — ${f.title}`);
    const meta = [f.category, f.line != null ? `line ${f.line}` : null].filter(Boolean).join(" · ");
    if (meta) out.push(`_${meta}_`, "");
    if (f.instruction) out.push("```dockerfile", f.instruction, "```", "");
    out.push(`**Why:** ${f.why}`);
    out.push(`**Fix:** ${f.fix}`);
    if (f.reference) out.push(`**Reference:** ${f.reference}`);
    out.push("");
  }

  if (report.passed_checks?.length) {
    out.push("## Passed checks", "");
    for (const c of report.passed_checks) out.push(`- ${c}`);
    out.push("");
  }

  out.push("---", "_Generated by DockerGuard — static analysis only._");
  return out.join("\n");
}

export function toPrintableHTML(report: AuditReport): string {
  const findings = sortFindings(report.findings ?? []);
  const rows =
    findings
      .map((f) => {
        const sev = normalizeSeverity(f.severity);
        const color = SEV_HEX[sev];
        const meta = [esc(f.category || ""), f.line != null ? `line ${f.line}` : ""]
          .filter(Boolean)
          .join(" · ");
        return `<div class="finding" style="border-left-color:${color}">
          <div class="fhead">
            <span class="badge" style="color:${color};border-color:${color}">${SEVERITY_LABEL[sev]}</span>
            <span class="ftitle">${esc(f.title)}</span>
            <span class="fmeta">${meta}</span>
          </div>
          ${f.instruction ? `<pre>${esc(f.instruction)}</pre>` : ""}
          <p class="why"><b>Why.</b> ${esc(f.why)}</p>
          <p class="fix"><b>Fix.</b> ${esc(f.fix)}</p>
        </div>`;
      })
      .join("") || "<p>No issues found.</p>";

  const passed = report.passed_checks?.length
    ? `<h2>Passed checks</h2><ul>${report.passed_checks.map((c) => `<li>${esc(c)}</li>`).join("")}</ul>`
    : "";

  return `<!doctype html><html lang="en"><head><meta charset="utf-8" />
  <title>DockerGuard report</title>
  <style>
    * { box-sizing: border-box; }
    body { font: 14px/1.55 -apple-system, "Segoe UI", Roboto, sans-serif; color: #111827; margin: 40px; max-width: 820px; }
    h1 { font-size: 22px; margin: 0 0 6px; letter-spacing: -0.02em; }
    h2 { font-size: 16px; margin: 28px 0 10px; border-bottom: 1px solid #eaecf0; padding-bottom: 6px; }
    .sub { color: #667085; margin: 0 0 16px; }
    .score { font-size: 30px; font-weight: 700; color: #111827; }
    .summary { background: #f9fafb; border: 1px solid #eaecf0; border-radius: 8px; padding: 12px 14px; margin: 14px 0; }
    .finding { border: 1px solid #eaecf0; border-left-width: 4px; border-radius: 8px; padding: 12px 14px; margin: 10px 0; }
    .fhead { display: flex; align-items: center; gap: 8px; }
    .ftitle { font-weight: 600; }
    .fmeta { margin-left: auto; color: #667085; font-size: 12px; font-family: ui-monospace, monospace; }
    .badge { font-size: 11px; text-transform: uppercase; border: 1px solid; border-radius: 4px; padding: 1px 6px; }
    pre { background: #f9fafb; border-radius: 6px; padding: 8px 10px; overflow: auto; font-family: ui-monospace, monospace; font-size: 12px; margin: 10px 0; }
    .why { color: #475467; margin: 8px 0 4px; }
    .fix { color: #111827; margin: 4px 0 0; }
    ul { padding-left: 18px; } li { margin: 2px 0; color: #475467; }
    @media print { body { margin: 16px; } }
  </style></head><body>
  <h1>DockerGuard audit report</h1>
  <p class="sub"><span class="score">${Number(report.score) || 0}</span>/100 · Grade ${esc(report.grade)} · ${esc(report.input_type)} · ${findings.length} finding${findings.length === 1 ? "" : "s"}</p>
  ${report.summary ? `<div class="summary">${esc(report.summary)}</div>` : ""}
  <h2>Findings</h2>
  ${rows}
  ${passed}
  <p class="sub" style="margin-top: 24px;">Generated by DockerGuard — static analysis only.</p>
  </body></html>`;
}
