/*
 * # Demo Primary
 * Primary demo flow for the Flowcell resilient client. Accepts a `query` string
 * (plus an optional `forceFail` test flag), runs it through a code-node gate
 * and a single LLM answer node, and returns `{ answer }`.
 *
 * ## Purpose
 * Acts as the "primary flow" that Flowcell's `resilientClient.execute()` calls
 * first. The `Code` node gives a live failure hook: sending `forceFail: true`
 * fails the run so the client can prove retry, circuit-breaker, and fallback
 * behavior against a deployed endpoint. Verified live: normal calls answer,
 * `forceFail` calls fail with `FLOWCELL_TEST_HOOK`.
 *
 * ## When To Use
 * - Use as the primary flow ID when constructing the resilient client.
 * - Use when you want the full-quality answer path (fallback only runs if this fails).
 * - Send `forceFail: true` when you want to exercise failure handling live.
 *
 * ## When Not To Use
 * - Do not use when the primary is known-unhealthy; the breaker will route to
 *   `demo-fallback` instead.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `query` | `string` | Yes | User query supplied to the trigger and passed through to the LLM node. |
 * | `forceFail` | `bool` | No | Test hook: when `true`, the `Code` node throws and the flow fails. |
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `answer` | `string` | Concise answer generated by the LLM node. |
 *
 * ## Dependencies
 * ### Upstream Flows
 * - None. Entry-point flow invoked via API request.
 *
 * ### Downstream Flows
 * - None. Returns directly to the caller.
 *
 * ### External Services
 * - Gemini (`gemini-3.5-flash-lite`) via `LLMNode` — see `@model-configs/demo-primary_llmnode-689_generative-model-name.ts`.
 *
 * ## Node Walkthrough
 * 1. `API Request` (`graphqlNode`) — receives `{ query, forceFail? }`.
 * 2. `Code` (`codeNode_936`) — runs `@scripts/demo-primary_code-node-936_code.ts`; throws on `forceFail: true`, else passes `{ query }` through.
 * 3. `Generate Text` (`LLMNode_689`) — system + user prompts from `@prompts/...`, reading `{{codeNode_936.output.query}}`.
 * 4. `API Response` (`graphqlResponseNode`) — maps `{ answer }` from `{{LLMNode_689.output.generatedResponse}}`.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | Empty answer | Missing `query` in trigger payload | Send a non-empty `query` string. |
 * | Flow fails with FLOWCELL_TEST_HOOK | `forceFail: true` was sent (intentional test hook) | Omit `forceFail` for normal calls; the resilient client uses this to prove retry/breaker behavior. |
 * | LLM node fails | Missing provider credentials | Verify the model-config credentials. |
 */

// Flow: demo-primary

// -- Meta --
export const meta = {
  "name": "Demo Primary",
  "description": "Primary demo flow for Flowcell: takes a query, generates a concise answer, returns it. Accepts forceFail to exercise failure handling live.",
  "tags": [
    "reliability",
    "resilience"
  ],
  "testInput": {
    "query": "What is a circuit breaker?"
  },
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": "",
  "author": {
    "name": "Krish Anand",
    "email": "Krishanand974@gmail.com"
  }
};

// -- Inputs --
export const inputs = {
  "LLMNode_689": [
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "type": "model"
    }
  ]
};

// -- References --
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "demo_primary_llmnode_689_system_0": "@prompts/demo-primary_llmnode-689_system_0.md",
    "demo_primary_llmnode_689_user_1": "@prompts/demo-primary_llmnode-689_user_1.md"
  },
  "modelConfigs": {
    "demo_primary_llmnode_689_generative_model_name": "@model-configs/demo-primary_llmnode-689_generative-model-name.ts"
  },
  "scripts": {
    "demo_primary_code_node_936_code": "@scripts/demo-primary_code-node-936_code.ts"
  }
};

// -- Nodes & Edges --
export const nodes = [
  {
    "id": "triggerNode_1",
    "type": "triggerNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlNode",
      "trigger": true,
      "values": {
        "id": "triggerNode_1",
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": "{\n  \"query\": \"string\",\n  \"forceFail\": \"bool\"\n}"
      }
    }
  },
  {
    "id": "codeNode_936",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "codeNode",
      "values": {
        "code": "@scripts/demo-primary_code-node-936_code.ts",
        "nodeName": "Code"
      }
    }
  },
  {
    "id": "LLMNode_689",
    "type": "dynamicNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "LLMNode",
      "values": {
        "tools": [],
        "prompts": [
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/demo-primary_llmnode-689_system_0.md"
          },
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7d",
            "role": "user",
            "content": "@prompts/demo-primary_llmnode-689_user_1.md"
          }
        ],
        "memories": "[]",
        "messages": "[]",
        "nodeName": "Generate Text",
        "attachments": "",
        "credentials": "",
        "generativeModelName": "@model-configs/demo-primary_llmnode-689_generative-model-name.ts"
      }
    }
  },
  {
    "id": "responseNode_triggerNode_1",
    "type": "responseNode",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "nodeId": "graphqlResponseNode",
      "values": {
        "id": "responseNode_triggerNode_1",
        "headers": "{\"content-type\":\"application/json\"}",
        "retries": "0",
        "nodeName": "API Response",
        "webhookUrl": "",
        "retry_delay": "0",
        "outputMapping": "{\n  \"answer\": \"{{LLMNode_689.output.generatedResponse}}\"\n}"
      }
    }
  }
];

export const edges = [
  {
    "id": "triggerNode_1-codeNode_936",
    "source": "triggerNode_1",
    "target": "codeNode_936",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "codeNode_936-LLMNode_689",
    "source": "codeNode_936",
    "target": "LLMNode_689",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "LLMNode_689-responseNode_triggerNode_1",
    "source": "LLMNode_689",
    "target": "responseNode_triggerNode_1",
    "sourceHandle": "bottom",
    "targetHandle": "top",
    "type": "defaultEdge"
  },
  {
    "id": "response-trigger_triggerNode_1",
    "source": "triggerNode_1",
    "target": "responseNode_triggerNode_1",
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger",
    "type": "responseEdge"
  }
];

export default { meta, inputs, references, nodes, edges };
