export const config = {
  api: {
    endpoint: process.env.LAMATIC_API_URL ?? "",
    projectId: process.env.LAMATIC_PROJECT_ID ?? "",
    apiKey: process.env.LAMATIC_API_KEY ?? "",
  },
  flows: {
    mouDrafter: {
      name: "MoU Drafter",
      workflowId: process.env.MOU_DRAFTER_FLOW_ID ?? "",
      inputSchema: {
        agreementTitle: "string",
        effectiveDate: "string",
        partyAName: "string",
        partyAType: "string",
        partyAAddress: "string",
        partyASignatory: "string",
        partyASignatoryRole: "string",
        partyAEmail: "string",
        partyBName: "string",
        partyBType: "string",
        partyBAddress: "string",
        partyBSignatory: "string",
        partyBSignatoryRole: "string",
        partyBEmail: "string",
        engagementType: "string",
        scopeOfWork: "string",
        deliverables: "string",
        totalFeeAmount: "number",
        totalFeeCurrency: "string",
        paymentSchedule: "string",
        paymentPreset: "string",
        customDepositPct: "number",
        customPaymentDays: "number",
        eventStart: "string",
        eventEnd: "string",
        eventStartTime: "string",
        eventEndTime: "string",
        eventVenue: "string",
        paymentTiming: "string",
        paymentTimingCustom: "string",
        taxesIncluded: "boolean",
        taxRatePct: "number",
        lateFeePctPerMonth: "number",
        cancellationPolicy: "string",
        cancellationTerms: "string",
        guestCountFinalDate: "string",
        extraGuestRate: "number",
        foodSafetyRequired: "boolean",
        allergyHandlingRequired: "boolean",
        confidentialityRequired: "boolean",
        confidentialitySurvivalYears: "number",
        ipOwnership: "string",
        ipPortfolioRights: "boolean",
        terminationPreset: "string",
        governingLaw: "string",
        disputeResolution: "string",
        disputeVenue: "string",
        insuranceRequired: "boolean",
        insuranceGenLiab: "number",
        insuranceProfIndem: "number",
        dataProtectionRequired: "boolean",
        subcontractingAllowed: "boolean",
        noPublicityRequired: "boolean",
        liabilityCapMultiplier: "number",
        additionalContext: "string",
      },
      outputSchema: {
        latex: "string",
        clauseJson: "object",
        warnings: "array",
        patternReport: "object",
      },
    },
  },
};
