"use client";
// app/error.tsx
// Next.js error boundary — shown when an unhandled error occurs in the page

import { useEffect } from "react";

/**
 * Next.js error boundary page displayed when an unhandled runtime error
 * propagates up from the main page segment.
 *
 * Logs the error to the console on mount and renders a user-friendly panel
 * with the error message and a "Try Again" button that calls the framework's
 * `reset` callback to re-render the failed segment.
 *
 * @param error  - The caught `Error` object, optionally carrying a `digest`
 *   hash generated by Next.js for server-side errors.
 * @param reset  - Callback provided by Next.js to retry rendering the
 *   segment that threw the error.
 * @returns A centred error panel with the error message and a retry button.
 */
export default function ErrorPage({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    // Log error to console for debugging (not sent anywhere)
    console.error("[TrustGuard AI Error]", error);
  }, [error]);

  return (
    <div className="flex min-h-screen items-center justify-center px-4">
      <div className="w-full max-w-md rounded-2xl border border-red-500/20 bg-red-500/5 backdrop-blur-sm p-8 text-center">
        <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-red-500/10 text-red-400">
          <svg className="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
        </div>
        <h1 className="text-lg font-semibold text-white mb-2">Something went wrong</h1>
        <p className="text-sm text-slate-400 mb-6">
          {error.message || "An unexpected error occurred. Please try again."}
        </p>
        <button
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-cyan-500/20 hover:shadow-cyan-500/30 transition-all"
        >
          Try Again
        </button>
      </div>
    </div>
  );
}
