/*
 * # Code Review Agent
 * A webhook-invoked Lamatic flow that fetches a public GitHub pull request diff, runs specialized AI review stages over it, and returns a structured code review used by the wider Code Review Agent system.
 *
 * ## Purpose
 * This flow is responsible for turning a GitHub pull request reference into an actionable review artifact. It accepts a repository owner, repository name, and pull request number, retrieves the changed-file diff from the GitHub REST API, extracts the patch content, and then submits that diff through a sequence of focused LLM review stages for bug analysis, security scanning, style checking, and final synthesis.
 *
 * The outcome is a structured review payload containing issue lists and a concise summary. That matters because the surrounding agent system is designed to present triaged feedback to developers quickly, with machine-readable fields that can be rendered in UI cards or consumed by downstream automation. Rather than returning a single unstructured paragraph, this flow produces category-specific findings that support faster review and decision-making.
 *
 * Within the broader agent pipeline, this is the primary execution flow rather than a subordinate helper. In plan-retrieve-synthesize terms, it combines retrieval and synthesis in one chain: the webhook trigger captures the user request, the GitHub API step retrieves current PR file data, the code step normalizes the diff, the intermediate LLM nodes perform specialized analyses, and the final LLM node synthesizes those findings into a summary response suitable for presentation or chaining.
 *
 * ## When To Use
 * - Use when a caller needs an AI-generated review of a public GitHub pull request.
 * - Use when the available inputs are `owner`, `repo`, and `pr_number` and the desired output is a structured review with bug, security, style, and summary fields.
 * - Use when the review must be grounded in the latest pull request file diff fetched live from GitHub rather than from a cached or indexed source.
 * - Use when the invoking client is an HTTP caller such as the Next.js UI described in the kit, or any orchestration layer able to hit the Lamatic webhook trigger.
 * - Use when the output needs to support severity-aware triage of likely defects and vulnerabilities.
 *
 * ## When Not To Use
 * - Do not use when the repository or pull request is private and the flow has not been extended with authenticated GitHub access.
 * - Do not use when the caller cannot provide all three required trigger inputs: `owner`, `repo`, and `pr_number`.
 * - Do not use when the task is to review full repository contents, historical commits, or branch state beyond the pull request file diff returned by GitHub.
 * - Do not use when a human-authored review or deterministic static analysis pipeline is required instead of LLM-based findings.
 * - Do not use when the target input is not a GitHub pull request reference, such as raw code pasted directly by a user or a non-GitHub code host.
 * - Do not use if the Lamatic deployment has not been configured with working text-generation model credentials for each LLM node.
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `owner` | `string` | Yes | GitHub account or organization that owns the repository. |
 * | `repo` | `string` | Yes | GitHub repository name containing the pull request. |
 * | `pr_number` | `string` | Yes | Pull request number to review. |
 *
 * The trigger schema declares all inputs as strings. In practice, `pr_number` is expected to be a numeric string that GitHub will accept in the pull request files endpoint. The flow assumes the repository is publicly accessible because the configured API request only includes generic GitHub headers and no authorization token. Input values are interpolated directly into the GitHub API URL, so callers should provide clean repository identifiers rather than full URLs or free-form text.
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `summary` | `string` | Concise overall assessment of the pull request generated by the final synthesis stage. |
 * | `bugs` | `array<object>` | Bug and logic-risk findings from `Bug_Analysis`, typically including `line`, `issue`, and `severity`. |
 * | `security` | `array<object>` | Security findings from `Security_Scan`, typically including `line`, `issue`, and `severity`. |
 * | `style` | `array<string>` | Style and readability observations from `Style_Check`. |
 * | `diff` | `string` | Consolidated pull request patch text produced by the code extraction step and used internally for analysis. |
 *
 * The flow’s effective output is a structured object assembled across the LLM stages, culminating in a final summary. The intermediate analysis nodes each emit JSON constrained by their schemas, so `bugs` and `security` are lists of structured findings while `style` is a list of strings. The `summary` field is plain prose. Because the flow graph ends after `Final_Merge` without an explicit response-mapping node shown in the source, callers should treat the final node output as canonical and regard earlier fields as available only if the deployment exposes cumulative node outputs or maps them into the API response.
 *
 * ## Dependencies
 * ### Upstream Flows
 * This is an entry-point flow. No upstream Lamatic flow must run before it.
 *
 * The only prerequisite is that the invoker supplies valid `owner`, `repo`, and `pr_number` values. In the wider system, the Next.js frontend or another HTTP client acts as the upstream caller, but not as a Lamatic flow dependency.
 *
 * ### Downstream Flows
 * No downstream Lamatic flows are defined as consuming this flow’s output.
 *
 * In the broader kit, the primary downstream consumer is the application layer, which reads the review result for UI rendering. That consumer is expected to use `summary`, `bugs`, `security`, and `style` to populate triage cards and overall review text.
 *
 * ### External Services
 * - GitHub REST API — fetches the list of files and patch content for the target pull request — no explicit credential is configured in this flow as provided
 * - Lamatic LLM execution — runs all four `InstructorLLMNode` analysis stages — requires deployed model access in Lamatic
 * - Configured text-generation model provider, described in the kit as Groq with `llama-3.3-70b-versatile` — generates structured review outputs — requires provider credential configured in Lamatic model settings
 *
 * ### Environment Variables
 * - `LAMATIC_API_KEY` — used by the external app or orchestrator to invoke the deployed Lamatic flow — not consumed directly by any node inside this flow
 *
 * ## Node Walkthrough
 * 1. `Webhook` (`triggerNode`) receives the request payload with `owner`, `repo`, and `pr_number`. This is the entry point for the flow and defines the trigger schema the caller must satisfy.
 *
 * 2. `API` (`dynamicNode` using `apiNode`) calls `https://api.github.com/repos/{{owner}}/{{repo}}/pulls/{{pr_number}}/files` with GitHub v3 accept headers and a `User-Agent` of `code-review-agent`. Its job is to fetch the changed-file metadata for the pull request, including each file’s patch content when GitHub provides it.
 *
 * 3. `Code` (`dynamicNode` using `codeNode`) runs the referenced script `@scripts/code-review-agent_code.ts` over the GitHub API response. It outputs a single `diff` string, which is the normalized, consolidated patch text extracted from the returned PR files and prepared for LLM consumption.
 *
 * 4. `Bug_Analysis` (`InstructorLLMNode`) takes the extracted `diff` and applies the system prompt `@prompts/bug-analysis-system.md` together with the flow-specific user prompt `@prompts/code-review-agent_bug-analysis_user.md`. It generates structured JSON under the `bugs` field, with each finding expected to include a `line`, `issue`, and `severity`.
 *
 * 5. `Security_Scan` (`InstructorLLMNode`) receives the prior context and analyzes the same pull request diff through security-focused prompts. It produces structured JSON under the `security` field, again using finding objects that typically include `line`, `issue`, and `severity`.
 *
 * 6. `Style_Check` (`InstructorLLMNode`) reviews the diff for code quality, readability, and style concerns using its own system and user prompts. Its schema is simpler than the earlier stages and returns a `style` array of strings rather than structured issue objects.
 *
 * 7. `Final_Merge` (`InstructorLLMNode`) synthesizes the prior review context into a final `summary` string. This node serves as the final presentation layer for the flow, producing the concise overall verdict that the UI can display alongside the category-specific findings.
 *
 * 8. The terminal `addNode` indicates the flow ends after `Final_Merge`. No additional branching or conditional logic is present in the source, so execution is strictly linear from retrieval through synthesis.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | Flow returns an error before analysis begins | Missing or malformed `owner`, `repo`, or `pr_number` in the webhook payload | Validate the request body at the caller and ensure all three fields are present as strings; pass a numeric string for `pr_number`. |
 * | GitHub API step returns `404 Not Found` | Repository or pull request does not exist, identifiers are wrong, or the PR is inaccessible | Confirm `owner`, `repo`, and `pr_number`; test the corresponding GitHub API endpoint manually; ensure the PR is public if unauthenticated access is being used. |
 * | GitHub API step returns rate-limit or access errors | Unauthenticated GitHub API usage has hit limits or the repository requires authentication | Add authenticated GitHub access in the flow if needed, reduce repeated calls, or retry later. |
 * | `diff` is empty or incomplete | The PR has no patchable file changes, GitHub omitted patches for large/binary files, or the extraction script filtered too aggressively | Test the PR against GitHub’s files API response, inspect whether `patch` fields are present, and update the extraction script if larger or nonstandard diffs must be handled. |
 * | LLM nodes fail to run | No valid model credential or provider configuration is attached to one or more `generativeModelName` inputs | Configure each `InstructorLLMNode` with a working text-generation model in Lamatic and verify provider credentials. |
 * | Final output contains only a summary or is missing intermediate fields | The deployment exposes only the terminal node output rather than cumulative node outputs | Add an explicit response-shaping step or output mapping if the API consumer requires `bugs`, `security`, and `style` in the final response payload. |
 * | Findings are low quality or obviously irrelevant | Prompt-model mismatch, weak diff extraction, or model context limitations on large PRs | Verify the prompt references, inspect the generated `diff`, and consider truncation strategy or a stronger model for larger pull requests. |
 * | Caller expects this flow to consume prior flow output | This flow is standalone and has no upstream Lamatic flow inputs | Invoke it directly with the webhook payload rather than attempting to chain from a nonexistent prerequisite flow. |
 *
 * ## Notes
 * - The flow executes all analysis stages sequentially, not in parallel. This simplifies context passing but increases total latency relative to a fan-out design.
 * - The `style` output is less structured than the `bugs` and `security` outputs, so downstream consumers should not assume a uniform schema across all finding categories.
 * - The GitHub request includes `Accept` and `User-Agent` headers but no authorization header. That is sufficient for many public repositories, but it reduces reliability under rate limits and excludes private PR review.
 * - The source includes references to model configs, prompts, and a code script, so the exact quality and shape of results also depend on those external assets being present and correctly wired in the Lamatic project.
 * - There is no explicit conditional handling for empty diffs, binary files, or oversized pull requests in the flow definition. Those cases rely on GitHub’s response shape, the extraction script, and the tolerance of the selected model.
 */

// Flow: code-review-agent

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Code Review Agent",
  "description": "",
  "tags": [],
  "testInput": "",
  "githubUrl": "",
  "documentationUrl": "",
  "deployUrl": ""
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {
  "InstructorLLMNode_312": [
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "type": "model",
      "mode": "instructor",
      "description": "Select the model to generate text based on the prompt.",
      "modelType": "generator/text",
      "required": true,
      "isPrivate": true,
      "defaultValue": [
        {
          "configName": "configA",
          "type": "generator/text",
          "provider_name": "",
          "credential_name": "",
          "params": {}
        }
      ],
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      }
    }
  ],
  "InstructorLLMNode_549": [
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "type": "model",
      "mode": "instructor",
      "description": "Select the model to generate text based on the prompt.",
      "modelType": "generator/text",
      "required": true,
      "isPrivate": true,
      "defaultValue": [
        {
          "configName": "configA",
          "type": "generator/text",
          "provider_name": "",
          "credential_name": "",
          "params": {}
        }
      ],
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      }
    }
  ],
  "InstructorLLMNode_538": [
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "type": "model",
      "mode": "instructor",
      "description": "Select the model to generate text based on the prompt.",
      "modelType": "generator/text",
      "required": true,
      "isPrivate": true,
      "defaultValue": [
        {
          "configName": "configA",
          "type": "generator/text",
          "provider_name": "",
          "credential_name": "",
          "params": {}
        }
      ],
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      }
    }
  ],
  "InstructorLLMNode_481": [
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "type": "model",
      "mode": "instructor",
      "description": "Select the model to generate text based on the prompt.",
      "modelType": "generator/text",
      "required": true,
      "isPrivate": true,
      "defaultValue": [
        {
          "configName": "configA",
          "type": "generator/text",
          "provider_name": "",
          "credential_name": "",
          "params": {}
        }
      ],
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      }
    }
  ]
};

// ── References ────────────────────────────────────────
// Cross-references to extracted resources in their own directories
// NOTE: Trigger widget settings are saved to triggers/widgets/ but NOT cross-referenced here
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "bug_analysis_system": "@prompts/bug-analysis-system.md",
    "security_scan_system": "@prompts/security-scan-system.md",
    "style_check_system": "@prompts/style-check-system.md",
    "final_merge_system": "@prompts/final-merge-system.md",
    "code_review_agent_bug_analysis_user": "@prompts/code-review-agent_bug-analysis_user.md",
    "code_review_agent_security_scan_user": "@prompts/code-review-agent_security-scan_user.md",
    "code_review_agent_style_check_user": "@prompts/code-review-agent_style-check_user.md",
    "code_review_agent_final_merge_user": "@prompts/code-review-agent_final-merge_user.md"
  },
  "modelConfigs": {
    "code_review_agent_bug_analysis": "@model-configs/code-review-agent_bug-analysis.ts",
    "code_review_agent_security_scan": "@model-configs/code-review-agent_security-scan.ts",
    "code_review_agent_style_check": "@model-configs/code-review-agent_style-check.ts",
    "code_review_agent_final_merge": "@model-configs/code-review-agent_final-merge.ts"
  },
  "scripts": {
    "code_review_agent_code": "@scripts/code-review-agent_code.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "data": {
      "modes": {},
      "nodeId": "webhookTriggerNode",
      "schema": {
        "repo": "string",
        "owner": "string",
        "pr_number": "string"
      },
      "values": {
        "nodeName": "Webhook"
      },
      "trigger": true
    },
    "type": "triggerNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 0
    },
    "selected": false
  },
  {
    "id": "apiNode_688",
    "data": {
      "label": "New",
      "logic": [],
      "modes": {},
      "nodeId": "apiNode",
      "values": {
        "id": "apiNode_688",
        "url": "https://api.github.com/repos/{{triggerNode_1.output.owner}}/{{triggerNode_1.output.repo}}/pulls/{{triggerNode_1.output.pr_number}}/files",
        "body": "",
        "method": "GET",
        "headers": "{\"Accept\":\"application/vnd.github.v3+json\",\"User-Agent\":\"code-review-agent\"}",
        "retries": "0",
        "nodeName": "API",
        "retry_delay": "0",
        "convertXmlResponseToJson": false
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 130
    },
    "selected": false
  },
  {
    "id": "codeNode_104",
    "data": {
      "label": "dynamicNode node",
      "logic": [],
      "modes": {},
      "nodeId": "codeNode",
      "schema": {
        "diff": "string"
      },
      "values": {
        "id": "codeNode_104",
        "code": "@scripts/code-review-agent_code.ts",
        "nodeName": "Code"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 260
    },
    "selected": false
  },
  {
    "id": "InstructorLLMNode_312",
    "data": {
      "label": "New",
      "modes": {},
      "nodeId": "InstructorLLMNode",
      "values": {
        "id": "InstructorLLMNode_312",
        "tools": [],
        "schema": "{\n  \"type\": \"object\",\n  \"properties\": {\n    \"bugs\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"type\": \"object\",\n        \"properties\": {\n          \"line\": {\n            \"type\": \"string\"\n          },\n          \"issue\": {\n            \"type\": \"string\"\n          },\n          \"severity\": {\n            \"type\": \"string\"\n          }\n        },\n        \"additionalProperties\": true\n      }\n    }\n  }\n}",
        "prompts": [
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/bug-analysis-system.md"
          },
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7d",
            "role": "user",
            "content": "@prompts/code-review-agent_bug-analysis_user.md"
          }
        ],
        "memories": "@model-configs/code-review-agent_bug-analysis.ts",
        "messages": "@model-configs/code-review-agent_bug-analysis.ts",
        "nodeName": "Bug_Analysis",
        "attachments": "@model-configs/code-review-agent_bug-analysis.ts",
        "generativeModelName": "@model-configs/code-review-agent_bug-analysis.ts"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 390
    },
    "selected": false
  },
  {
    "id": "InstructorLLMNode_549",
    "data": {
      "label": "New",
      "modes": {},
      "nodeId": "InstructorLLMNode",
      "values": {
        "id": "InstructorLLMNode_549",
        "tools": [],
        "schema": "{\n  \"type\": \"object\",\n  \"properties\": {\n    \"security\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"type\": \"object\",\n        \"properties\": {\n          \"line\": {\n            \"type\": \"string\"\n          },\n          \"issue\": {\n            \"type\": \"string\"\n          },\n          \"severity\": {\n            \"type\": \"string\"\n          }\n        },\n        \"additionalProperties\": true\n      }\n    }\n  }\n}",
        "prompts": [
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/security-scan-system.md"
          },
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7d",
            "role": "user",
            "content": "@prompts/code-review-agent_security-scan_user.md"
          }
        ],
        "memories": "@model-configs/code-review-agent_security-scan.ts",
        "messages": "@model-configs/code-review-agent_security-scan.ts",
        "nodeName": "Security_Scan",
        "attachments": "@model-configs/code-review-agent_security-scan.ts",
        "generativeModelName": "@model-configs/code-review-agent_security-scan.ts"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 520
    },
    "selected": false
  },
  {
    "id": "InstructorLLMNode_538",
    "data": {
      "label": "New",
      "modes": {},
      "nodeId": "InstructorLLMNode",
      "values": {
        "id": "InstructorLLMNode_538",
        "tools": [],
        "schema": "{\n  \"type\": \"object\",\n  \"properties\": {\n    \"style\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"type\": \"string\"\n      }\n    }\n  }\n}",
        "prompts": [
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/style-check-system.md"
          },
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7d",
            "role": "user",
            "content": "@prompts/code-review-agent_style-check_user.md"
          }
        ],
        "memories": "@model-configs/code-review-agent_style-check.ts",
        "messages": "@model-configs/code-review-agent_style-check.ts",
        "nodeName": "Style_Check",
        "attachments": "@model-configs/code-review-agent_style-check.ts",
        "generativeModelName": "@model-configs/code-review-agent_style-check.ts"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 650
    },
    "selected": true
  },
  {
    "id": "plus-node-addNode_846235",
    "data": {
      "label": "+",
      "nodeId": "addNode",
      "values": {}
    },
    "type": "addNode",
    "measured": {
      "width": 216,
      "height": 100
    },
    "position": {
      "x": 0,
      "y": 910
    }
  },
  {
    "id": "InstructorLLMNode_481",
    "data": {
      "label": "New",
      "modes": {},
      "nodeId": "InstructorLLMNode",
      "values": {
        "id": "InstructorLLMNode_481",
        "tools": [],
        "schema": "{\n  \"type\": \"object\",\n  \"properties\": {\n    \"summary\": {\n      \"type\": \"string\"\n    }\n  }\n}",
        "prompts": [
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7b",
            "role": "system",
            "content": "@prompts/final-merge-system.md"
          },
          {
            "id": "187c2f4b-c23d-4545-abef-73dc897d6b7d",
            "role": "user",
            "content": "@prompts/code-review-agent_final-merge_user.md"
          }
        ],
        "memories": "@model-configs/code-review-agent_final-merge.ts",
        "messages": "@model-configs/code-review-agent_final-merge.ts",
        "nodeName": "Final_Merge",
        "attachments": "@model-configs/code-review-agent_final-merge.ts",
        "generativeModelName": "@model-configs/code-review-agent_final-merge.ts"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 780
    },
    "selected": false
  }
];

export const edges = [
  {
    "id": "InstructorLLMNode_312-InstructorLLMNode_549-380",
    "type": "defaultEdge",
    "source": "InstructorLLMNode_312",
    "target": "InstructorLLMNode_549",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "InstructorLLMNode_549-InstructorLLMNode_538-415",
    "type": "defaultEdge",
    "source": "InstructorLLMNode_549",
    "target": "InstructorLLMNode_538",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "triggerNode_1-apiNode_688-888",
    "type": "defaultEdge",
    "source": "triggerNode_1",
    "target": "apiNode_688",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "apiNode_688-codeNode_104-909",
    "type": "defaultEdge",
    "source": "apiNode_688",
    "target": "codeNode_104",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "codeNode_104-InstructorLLMNode_312-743",
    "type": "defaultEdge",
    "source": "codeNode_104",
    "target": "InstructorLLMNode_312",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "InstructorLLMNode_538-InstructorLLMNode_481-685",
    "type": "defaultEdge",
    "source": "InstructorLLMNode_538",
    "target": "InstructorLLMNode_481",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "InstructorLLMNode_481-plus-node-addNode_846235-985",
    "type": "defaultEdge",
    "source": "InstructorLLMNode_481",
    "target": "plus-node-addNode_846235",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  }
];

export default { meta, inputs, references, nodes, edges };
